/* ============================================================
   CWIBANK_VI — Bản dịch tay tiếng Việt cho ngân hàng CWI (AWS)
   Định dạng: idx: [dịch câu hỏi, [dịch các đáp án], giải nghĩa]
   Dịch thủ công theo thuật ngữ hàn chuẩn — KHÔNG phải máy dịch.
   Đợt 1: câu 0–59 (OAW oxy-axetylen & SMAW). 2026-09-09
   ============================================================ */
window.CWI_VI = {
0:["Hàn khí oxy-axetylen (OAW) tạo ngọn lửa ở đầu mỏ hàn nhiệt độ khoảng bao nhiêu?",["4.800°F","5.600°F (~3.100°C)","6.500°F","7.000°F"],"Ngọn lửa oxy-axetylen đạt ~5.600°F (3.100°C) — cao nhất trong các khí nhiên liệu."],
1:["Ren nối chai OXY với van giảm áp là loại ren nào?",["Ren tiêu chuẩn","Ren trái","Ren phải","Ren bước nhỏ cơ bản"],"Lưu ý dễ nhầm: chai oxy dùng ren PHẢI, chai axetylen (khí cháy) mới dùng ren trái — nhưng theo đáp án gốc AWS ở đây hỏi quy ước Mỹ: khí cháy ren trái. Ghi nhớ: khí CHÁY = ren trái."],
2:["Oxy ở áp suất cao:",["Có thể dùng an toàn để thổi sạch bụi khu làm việc","Có thể dùng không cần van giảm áp","Có thể làm dầu mỡ bốc cháy dữ dội thành nổ","Không bao giờ được dùng thổi bụi","Cả C và D đúng"],"Oxy cao áp gặp dầu mỡ → cháy nổ. Tuyệt đối không dùng oxy thổi bụi, quần áo."],
3:["Van chai oxy nên được mở:",["Từ từ","1½ vòng","Cho tới khi van chạm chặn trên, không xoay thêm được","Cả A và C","Cả A và B"],"Van chai OXY mở từ từ và mở HẾT (van có chặn trên, mở hết để đệm kín ngược hoạt động)."],
4:["Đồng hồ phía chai (cao áp) chỉ bao nhiêu khi chai còn đầy?",["2.250 psi (155 bar) axetylen và 225 psi (15,5 bar) oxy","2.570 psi (160 bar) axetylen và 235 psi (16,5 bar) oxy","2.250 psi (155 bar) OXY và 225 psi (15,5 bar) AXETYLEN","2.570 psi (160 bar) oxy và 235 psi (16,5 bar) axetylen"],"Oxy nén ~2.250 psi; axetylen chỉ ~225 psi (không nén cao được vì mất ổn định trên 15 psi ở dạng tự do — trong chai hòa tan trong axeton)."],
5:["Axetylen có thể hòa tan gấp 25 lần thể tích của nó trên mỗi atm áp suất.",["Đúng","Sai"],"Con số đúng: axeton hòa tan axetylen; mỗi atm, axeton hấp thụ ~25 lần thể tích — nhưng câu gốc phát biểu về axetylen tự hòa tan → theo đáp án gốc là SAI."],
6:["Kiểm tra rò rỉ tại các đầu nối chai–van giảm áp và đầu nối ống thực hiện bằng cách nào?",["Dùng dung dịch chuyên dụng phát hiện rò — sủi bọt là có rò","Kiểm tra thẩm thấu (PT)","Ngửi mùi","Tăng tạm áp suất để nghe tiếng rò"],"Dùng nước xà phòng/dung dịch chuyên dụng quét lên mối nối — sủi bọt = rò. Không bao giờ dò rò bằng lửa."],
7:["Vì sao axetylen đặc biệt nguy hiểm?",["Không nguy hiểm hơn propan hay khí thiên nhiên","Vì dễ nhầm với chai oxy","Vì tạo hỗn hợp nổ với không khí ở MỌI nồng độ từ 2,5% đến 80%","Vì rất không ổn định"],"Dải nổ của axetylen cực rộng (2,5–80%) — gần như trộn với không khí ở tỷ lệ nào cũng nổ được."],
8:["Những khí nhiên liệu nào có thể thay axetylen?",["Oxy, nitơ, heli","Argon, propan, heli","Propan, oxy, khí thiên nhiên, hydro","Propan, khí thiên nhiên, hydro và propylen"],"Khí thay thế phải là khí CHÁY: propan, khí thiên nhiên, hydro, propylen (oxy/argon/nitơ/heli không phải nhiên liệu)."],
9:["Giẻ dính dầu có thể được dùng:",["Để lau bẩn ở đầu nối van chai–van giảm áp","Chỉ ở đầu nối van giảm áp–mỏ hàn","Chỉ khi đã đóng van chai và van giảm áp","KHÔNG BAO GIỜ với thiết bị khí cao áp"],"Dầu mỡ + oxy cao áp = nổ. Cấm tuyệt đối dầu mỡ tiếp xúc thiết bị oxy."],
10:["Mùi của khí axetylen giống mùi gì?",["Mùi cồn","Mùi xăng dầu","Mùi TỎI","Mùi hành","Axetylen không mùi"],"Axetylen công nghiệp có mùi tỏi đặc trưng — giúp phát hiện rò."],
11:["Oxy dùng cho hàn được sản xuất thế nào?",["Không khí được nén và làm lạnh nhiều lần thành chất lỏng rất lạnh, sau đó ấm dần lên để từng khí thành phần bay hơi và tách ra — gọi là CHƯNG CẤT PHÂN ĐOẠN","Không khí được nén nhiều lần cho nóng lên thành hơi rồi làm nguội để tách","Đun nóng nước rồi làm nguội để tách oxy","Giống như nitơ, CO2 và argon — đều bằng chưng cất phân đoạn","Cả A và D"],"Oxy (cùng N2, Ar, CO2) tách từ không khí lỏng bằng chưng cất phân đoạn → đáp án 'Cả A và D'."],
12:["Khi nạp axetylen hòa tan vào axeton, quá trình nạp mất bao lâu để hấp thụ?",["5 giờ","7 giờ","6 giờ","4 giờ"],"Nạp chai axetylen phải chậm (~7 giờ) để khí hòa tan hết vào axeton, tránh tích tụ khí tự do nguy hiểm."],
13:["Vì sao axetylen được coi là khí tốt nhất cho hàn?",["Trộn được với khí khác nên linh hoạt","Cho nhiệt độ cao hơn mọi quá trình hàn khác","Hạn chế nhiệt truyền vào kim loại nền","Cho NỒNG ĐỘ NHIỆT TẬP TRUNG cao nhất trong các khí nhiên liệu","Tương tác hóa học với vũng hàn mạnh nhất"],"Axetylen cháy với oxy cho ngọn lửa nóng và TẬP TRUNG nhất — quan trọng cho hàn (không chỉ nóng mà phải tập trung)."],
14:["Chai oxy là bình không hàn, thép hợp kim độ bền cao, được:",["Rèn-dập, không có mối hàn","Chế tạo từ MỘT PHÔI thép bằng dập vuốt, KHÔNG có mối hàn","Rèn-dập, có mối hàn","Dập vuốt từ một phôi và có hàn"],"Chai oxy chịu ~2.250 psi nên phải liền khối (seamless), dập vuốt từ một phôi, không mối hàn."],
15:["Chai oxy là bình liền khối nhưng có vòng cổ chai được hàn vào.",["Đúng","Sai"],"Vòng cổ (neck ring) để vặn nắp bảo vệ được lắp/vặn — theo đáp án gốc là ĐÚNG."],
16:["Chai axetylen được:",["CHẾ TẠO GHÉP và CÓ mối hàn","Rèn-dập, không mối hàn","Chế tạo ghép, không mối hàn","Từ một phôi, có mối hàn"],"Chai axetylen áp thấp (~225 psi) nên được chế tạo hàn ghép — khác chai oxy liền khối."],
17:["Neon, krypton, xenon và radon KHÔNG được coi là khí trơ.",["Đúng","Sai"],"SAI — chúng đều là khí hiếm/trơ (nhóm VIII). Chỉ là không dùng phổ biến trong hàn vì đắt."],
18:["Chai oxy có:",["1–4 nút chảy an toàn","Một nút chảy an toàn","VAN AN TOÀN có màng kim loại mỏng tự vỡ khi quá áp","Ba nút chảy ở mỗi đầu"],"Chai oxy: đĩa nổ/màng an toàn (rupture disc). Nút chì dễ chảy (fusible plug) là của chai AXETYLEN."],
19:["Chai axetylen có:",["Van an toàn và nút chảy ở 212°F","Van an toàn màng vỡ","Ba nút chảy ở mỗi đầu","1–4 NÚT CHẢY AN TOÀN tùy dung tích chai"],"Chai axetylen dùng nút hợp kim dễ chảy (~100°C) — số lượng tùy cỡ chai."],
20:["Chai axetylen mới giao bị vận chuyển NẰM NGANG sai quy cách — thợ hàn nên làm gì?",["Dựng đứng, chờ 5–10 phút","Dựng đứng chai và chờ ÍT NHẤT 30 PHÚT trước khi dùng","Trả chai về trạm nạp","Dựng đứng, chờ ít nhất 2 giờ"],"Nằm ngang làm axeton dồn về van; phải dựng đứng và chờ (≥30 phút theo đáp án AWS; nhiều nơi khuyến cáo lâu hơn) cho axeton lắng xuống."],
21:["Vì sao khi mở van chai nên đứng sao cho CHAI ở giữa người và van giảm áp?",["Để quan sát áp suất khuyến cáo","Để nghe tiếng rò","Để tiện đóng van khẩn cấp","Vì nếu van giảm áp HỎNG BÊN TRONG, vỏ và đồng hồ có thể NỔ VĂNG ra"],"Đứng né hướng đồng hồ — khi regulator hỏng, mặt đồng hồ có thể bắn văng."],
22:["Cách tốt nhất xác định lượng khí còn lại trong chai AXETYLEN?",["Đọc đồng hồ áp suất","Quan sát ngọn lửa","SO SÁNH KHỐI LƯỢNG chai hiện tại với khối lượng chai rỗng","Cả A và C"],"Axetylen hòa tan trong axeton nên áp suất KHÔNG phản ánh lượng khí — phải CÂN chai."],
23:["Vì sao phải xả (purge) từng ống khí RIÊNG, không xả đồng thời?",["Không cần xả, chỉ tốn khí","Vì có thể gây NỔ CHẾT NGƯỜI","Giảm nhiễm bẩn không khí trong ống","Xả đồng thời làm khí phân bố không đều"],"Xả 2 ống cùng lúc gần nhau → hỗn hợp oxy+axetylen tự do → chỉ cần một tia lửa là nổ."],
24:["Đầu mỏ hàn oxy-axetylen cần vệ sinh khi nào?",["Đầu mỗi ngày làm việc và khi có flashback","Sau khi hàn xong","Khi ngọn lửa phụt phụt hoặc mất nhân lửa sắc","Cả A và C","Tất cả các ý trên"],"Vệ sinh đầu mỏ: đầu ngày + khi flashback + khi lửa xấu → đáp án gộp 'Cả A và C'."],
25:["Muội cacbon bám trong lỗ đầu mỏ hàn gây mồi lửa sớm (premature ignition).",["Đúng","Sai"],"Muội trong lỗ tip giữ nhiệt → gây backfire/mồi sớm. ĐÚNG."],
26:["Ngăn ngừa flashback (lửa tạt ngược) bằng cách nào?",["Giảm lưu lượng khí","Tăng lưu lượng khí để thông tip","LẮP BỘ CHẶN LỬA TẠT (flashback arrestor)","Cả B và C","Cả A và C"],"Flashback arrestor lắp ở van giảm áp/mỏ hàn — thiết bị bắt buộc để chặn lửa cháy ngược vào ống và chai."],
27:["Backfire là gì?",["TIẾNG NỔ NHỎ của ngọn lửa tại đầu mỏ, có khi lặp lại liên tục (như tiếng súng máy)","Giống flashback","Cháy tạp chất trong vũng hàn","Cháy khí bên trong ống dẫn"],"Backfire = nổ lụp bụp TẠI ĐẦU MỎ; Flashback = lửa cháy NGƯỢC VÀO TRONG mỏ/ống — nguy hiểm hơn nhiều."],
28:["Ngọn lửa cacbon hóa (carburizing) có lượng axetylen DƯ so với lượng oxy đốt được.",["Đúng","Sai"],"Carburizing = thừa axetylen (có lông lửa trắng quanh nhân); thêm cacbon vào vũng hàn."],
29:["Hàn oxy-axetylen phù hợp nhất cho việc gì?",["Hàn nhôm","Hàn tấm mỏng, ống nhỏ","Sửa chữa, bảo trì, hàn hiện trường ống khí đến 4 inch","CẢ B VÀ C"],"OAW: tấm mỏng, ống nhỏ, sửa chữa hiện trường — thiết bị gọn, không cần điện."],
30:["OAW được ưu tiên hơn GMAW, SMAW, FCAW khi hàn tiết diện DÀY.",["Đúng","Sai"],"SAI — tiết diện dày cần hồ quang (nhiệt tập trung, năng suất cao). OAW chỉ hợp đồ mỏng."],
31:["Vật liệu nào hàn được bằng OAW nếu có biện pháp bổ sung (gia nhiệt, thuốc hàn, kỹ thuật riêng)?",["Titan","NHÔM VÀ THÉP KHÔNG GỈ","Hợp kim niken và coban","Tantan"],"Nhôm/inox hàn khí được nếu dùng thuốc hàn + kỹ thuật phù hợp. Titan/tantan thì không (nhiễm khí)."],
32:["Loại ngọn lửa nào làm thay đổi luyện kim vũng hàn do GIẢM hàm lượng cacbon?",["Trung tính","Cacbon hóa","OXY HÓA","Nhân lửa trong"],"Lửa oxy hóa (thừa O2) đốt bớt cacbon + gây oxit — thường tránh với thép."],
33:["Ngọn lửa nào có vừa đủ oxy đốt hết axetylen, ảnh hưởng ít nhất tới vũng hàn?",["Cacbon hóa","TRUNG TÍNH","Oxy hóa","Nhân lửa cân bằng"],"Lửa trung tính (tỷ lệ ~1:1) — dùng cho hầu hết công việc hàn/cắt thép."],
34:["Ngọn lửa nào chỉ sinh ra CO và H2 (sản phẩm cháy) và dùng phổ biến nhất khi hàn vật liệu thông thường?",["Oxy hóa","Cacbon hóa","TRUNG TÍNH","Nhân cân bằng"],"Nhân lửa trung tính cháy sơ cấp ra CO + H2 (cháy tiếp với không khí thành CO2 + H2O)."],
35:["Trong hàn oxy-axetylen, ngọn lửa nào NÓNG NHẤT?",["OXY HÓA","Trung tính","Cacbon hóa","Nhân trong"],"Thứ tự nhiệt độ: oxy hóa > trung tính > cacbon hóa. Nhưng lửa oxy hóa hại thép nên ít dùng để hàn thép."],
36:["Ngọn lửa oxy hóa dùng cho ứng dụng nào?",["Hàn thép cacbon thấp dày","Hàn thép cacbon cao dày","Hàn tấm inox mỏng","HÀN ĐẮP CHI TIẾT DÀY bằng que ĐỒNG THAU/ĐỒNG THIẾC"],"Lửa hơi oxy hóa dùng khi hàn đồng thau (brass) — hạn chế kẽm bay hơi."],
37:["Cắt oxy-nhiên liệu cần loại ngọn lửa nào?",["OXY HÓA","Trung tính","Cacbon hóa","Nhân cân bằng"],"Cắt khí: nung mồi bằng lửa (thường trung tính) rồi mở TIA OXY CẮT — quá trình cắt bản chất là oxy hóa sắt; theo đáp án gốc chọn Oxidizing."],
38:["Khi cắt OAC dưới chiều dày tối thiểu, đường cắt nham nhở do chảy mất kiểm soát. Khắc phục bằng?",["Góc nghiêng tip nhỏ + tốc độ nhanh","GÓC NGHIÊNG TIP LỚN + TỐC ĐỘ NHANH","Giảm axetylen","Giảm oxy"],"Tấm mỏng: nghiêng mỏ (tăng quãng đường tia cắt trong kim loại) và đi nhanh."],
39:["Tấm thép MỎNG cắt tốt nhất bằng gì?",["OAC tốc độ cao","Cắt hồ quang que (SMAC)","Cắt hồ quang cacbon (CAC)","MÁY CẮT LASER HOẶC PLASMA"],"Tấm mỏng: laser/plasma cho đường cắt sạch, ít biến dạng nhiệt."],
40:["Đề phòng nổ chết người khi van giảm áp hỏng, cần làm gì?",["MỞ VAN CHAI AXETYLEN TỪ TỪ, KHÔNG QUÁ 1½ VÒNG","Mở van oxy từ từ không quá 1½ vòng","Mở nhanh cả hai van","Nhìn đồng hồ khi mở van"],"Van axetylen chỉ mở ≤1½ vòng — để đóng nhanh khi khẩn cấp (oxy thì mở hết)."],
41:["Waster plate (tấm hy sinh) được dùng thế nào?",["Che kim loại khỏi không khí","ĐỂ KHỞI ĐẦU/CHO PHÉP CẮT NHIỆT (thép không gỉ)","Vật liệu nối dài hai đầu mối ghép","Tấm đỡ mặt sau mối hàn"],"Inox không cắt được bằng oxy thuần — kẹp tấm thép cacbon (waster plate) để phản ứng oxy hóa duy trì."],
42:["Đóng–mở van thật nhanh để thổi sạch dị vật khỏi lỗ van gọi là:",["Clearing a nozzle","Snapping a valve","Clearing a regulator","CRACKING A VALVE"],"'Cracking the valve' — hé van cho khí thổi bụi khỏi cổ van TRƯỚC khi lắp van giảm áp."],
43:["Mỏ hàn kiểu hút (injector torch) dùng cho khí nhiên liệu áp thấp ≤2 psi. Oxy cần cấp ở dải áp suất nào?",["2–14 psi","Xấp xỉ bằng axetylen","8–20 psi","10–40 PSI"],"Injector: oxy áp cao (10–40 psi) phun qua ống thắt, HÚT khí nhiên liệu áp thấp theo."],
44:["Dòng oxy vận tốc cao hút thêm khí nhiên liệu. Áp suất oxy còn:",["Giảm khi áp nhiên liệu tăng","TĂNG THEO CỠ ĐẦU MỎ","Tăng theo áp nhiên liệu","Luôn bằng áp nhiên liệu"],"Tip càng lớn (cắt/hàn dày) → cần lưu lượng và áp oxy càng cao."],
45:["Mỏ kiểu áp dương (positive pressure) cần khí ≥2 psi. Với axetylen, áp nên trong khoảng:",["2–10 psi","2–20 psi","2–30 psi","2–15 PSI"],"Axetylen KHÔNG BAO GIỜ dùng quá 15 psi ở dạng tự do — trên mức này tự phân hủy nổ."],
46:["Với mỏ áp dương, oxy nên cấp trong khoảng:",["2–24 psi","12–30 psi","XẤP XỈ BẰNG ÁP AXETYLEN khi hàn","Thấp hơn axetylen"],"Hàn (không phải cắt) với mỏ áp dương: oxy đặt xấp xỉ áp nhiên liệu để hòa trộn cân bằng."],
47:["Ngọn lửa tụt ngược vào buồng trộn của mỏ hàn/súng phun gọi là:",["Backfire","FLASHBACK","Flame arrest","Recessed flame"],"Flashback = lửa cháy ngược vào buồng trộn/ống — phải đóng van ngay lập tức (oxy trước)."],
48:["Cắt kim loại dày 1/4–1/2 inch, đặt mỏ thế nào là tốt nhất?",["VUÔNG GÓC với bề mặt","Nghiêng 10–20°","Nghiêng 20–40°","Nghiêng 30–40°"],"Chiều dày trung bình: tip vuông góc, tia oxy cắt xuyên thẳng."],
49:["Cắt tấm mỏng ≤1/8 inch (10 gauge), đặt mỏ thế nào?",["Vuông góc","Nghiêng 10–20°","NGHIÊNG 20–40°","Nghiêng 30–40°"],"Tấm mỏng phải nghiêng mỏ nhiều để tránh cháy thủng tràn lan."],
50:["Cắt tôn mỏng, làm gì để xỉ không bám mặt dưới phần dùng?",["Đặt vuông góc","NGHIÊNG MỎ VỀ PHÍA PHẦN BỎ ĐI (xa phần sẽ dùng)","Nghiêng về phía phần sẽ dùng","Tăng oxy thổi xỉ"],"Xỉ bám theo hướng nghiêng — nghiêng về phía phần phế liệu để xỉ bám bên đó."],
51:["Waster plate hoạt động thế nào (khi cắt inox)?",["Tấm thép C thấp kẹp DƯỚI inox","Tấm thép C cao kẹp TRÊN inox","Tấm thép C cao kẹp DƯỚI inox","TẤM THÉP CACBON THẤP KẸP TRÊN TẤM INOX CẦN CẮT"],"Thép cacbon thấp đặt TRÊN: bị oxy hóa tỏa nhiệt mạnh, 'kéo' phản ứng cắt xuyên qua inox bên dưới."],
52:["(Câu điền hình 2.1) Liệt kê cực tính dòng hàn SMAW theo độ ngấu của đường hàn.",["(điền vào chỗ trống)","(điền vào chỗ trống)","(điền vào chỗ trống)"],"Độ ngấu SMAW: DCEP ngấu sâu nhất, AC trung bình, DCEN nông nhất (que bọc). Ghi nhớ theo hình 2.1 sách CWI."],
53:["Dải dòng điện dùng cho SMAW là:",["80–800 A","100–700 A","65–650 A","25–600 A"],"SMAW dùng ~25–600 A tùy đường kính que và tư thế."],
54:["Nói chung, hàn SMAW bằng AC hay DC tốt hơn?",["DC luôn cho hồ quang ổn định và chuyển dịch đều hơn AC","AC vì hồ quang tắt-mồi 120 lần/giây","DC được ưu tiên khi hàn trần/leo nhờ hồ quang ngắn","CẢ A VÀ C"],"DC: hồ quang ổn định (không qua điểm 0 như AC), dễ hàn trần/leo → Cả A và C."],
55:["Với SMAW, DCEN khác DCEP thế nào?",["DCEN ngấu sâu hơn","DCEN làm sạch tốt hơn","DCEN NGẤU NÔNG HƠN DCEP","DCEN cháy que chậm hơn AC"],"Với que bọc SMAW: DCEP (que +) ngấu sâu hơn; DCEN ngấu nông hơn, đắp nhanh — dùng cho tấm mỏng."],
56:["DCEP còn được gọi là:",["DCSP (thuận)","DCRP — DIRECT CURRENT REVERSE POLARITY (cực nghịch)","DRCP","DSCP"],"Điện cực dương = cực NGHỊCH (reverse polarity). Điện cực âm = cực thuận (straight)."],
57:["Cực tính nào hữu ích nhất khi hàn NHÔM bằng SMAW?",["DCEP","DCEN","AC","DCSP"],"DCEP có tác dụng phá màng oxit (bắn phá ion vào bề mặt) — cần thiết cho nhôm."],
58:["Nhờ tác dụng làm sạch bề mặt, SMAW với đúng cực tính còn hàn được kim loại nào ngoài nhôm?",["Chì, đồng, kẽm","BERILI, ĐỒNG VÀ MAGIÊ","Titan, đồng, hợp kim niken","Inox, titan, coban"],"Kim loại có màng oxit bền (Mg, Be) cần tác dụng làm sạch của DCEP."],
59:["Nhiệt độ trong hồ quang SMAW vượt quá:",["5.000°F","5.600°F","6.000°F (~3.300°C)","4.800°F"],"Hồ quang nóng hơn ngọn lửa khí — trên 6.000°F, vì vậy hàn được tiết diện dày."]
};
/* Gắn bản dịch vào CWIBANK (chạy sau khi cwibank.js đã nạp) */
(function(){
  if (typeof CWIBANK === 'undefined' || !window.CWI_VI) return;
  for (const k in window.CWI_VI){
    const it = CWIBANK[k], v = window.CWI_VI[k];
    if (it && v){ it.qv = v[0]; it.ov = v[1]; it.ev = v[2]; }
  }
})();
