/* ============================================================
   GLOSSARY — Từ điển thuật ngữ hàn CSWIP 3.1 (EN → VI)
   Dùng cho tính năng bôi đen → dịch (tra offline).
   Key viết thường; tra cả cụm từ và từ đơn trong đoạn bôi đen.
   ============================================================ */
window.GLOSSARY = {
/* ---------- Vai trò, hồ sơ, tiêu chuẩn ---------- */
"welding inspector":"thanh tra hàn / giám sát hàn",
"specification":"tiêu chuẩn kỹ thuật, chỉ dẫn kỹ thuật",
"code":"quy phạm, bộ tiêu chuẩn",
"standard":"tiêu chuẩn",
"procedure":"quy trình",
"wps":"quy trình hàn (Welding Procedure Specification)",
"pqr":"biên bản chứng nhận quy trình hàn (Procedure Qualification Record)",
"wpqr":"biên bản chứng nhận quy trình hàn",
"welder qualification":"chứng chỉ thợ hàn",
"welder approval":"phê duyệt/chứng nhận thợ hàn",
"documentation":"hồ sơ, tài liệu",
"traceability":"truy xuất nguồn gốc",
"compliance":"sự phù hợp / tuân thủ",
"acceptance criteria":"tiêu chí chấp nhận",
"non-conformance":"sự không phù hợp",
"concession":"nhân nhượng (chấp nhận sai lệch có phê duyệt)",
"quality control":"kiểm soát chất lượng (QC)",
"quality assurance":"đảm bảo chất lượng (QA)",
"data book":"hồ sơ hoàn công",
"release note":"chứng chỉ xuất xưởng vật liệu",
"mill certificate":"chứng chỉ nhà máy (vật liệu)",
"test certificate":"chứng chỉ thử nghiệm",
"scope of work":"phạm vi công việc",
"duty":"nhiệm vụ",
"witness":"chứng kiến (giám sát thử nghiệm)",
"hold point":"điểm dừng chờ (bắt buộc có mặt nghiệm thu)",
"monitor":"theo dõi, giám sát",

/* ---------- Liên kết hàn, chuẩn bị mép ---------- */
"joint":"liên kết, mối ghép",
"butt joint":"liên kết giáp mối",
"tee joint":"liên kết chữ T",
"lap joint":"liên kết chồng",
"corner joint":"liên kết góc",
"edge joint":"liên kết mép",
"butt weld":"mối hàn giáp mối",
"fillet weld":"mối hàn góc",
"groove":"rãnh hàn",
"bevel":"vát mép (một phía)",
"bevel angle":"góc vát mép",
"included angle":"góc rãnh (tổng hai góc vát)",
"root face":"mặt đáy (chiều dày mép cùn)",
"root gap":"khe hở đáy",
"root radius":"bán kính đáy (rãnh chữ J/U)",
"land":"mép cùn (root face)",
"single v":"rãnh chữ V một phía",
"double v":"rãnh chữ V hai phía (chữ X)",
"single u":"rãnh chữ U một phía",
"j preparation":"vát mép chữ J",
"joint preparation":"chuẩn bị mép hàn",
"fit-up":"gá lắp, lắp ráp mối ghép",
"alignment":"sự thẳng hàng, đồng tâm",
"misalignment":"lệch mép (hi-lo)",
"tack weld":"hàn đính",
"backing bar":"tấm lót đáy",
"backing strip":"dải lót đáy",
"back gouging":"dũi đáy (moi đáy trước khi hàn mặt sau)",
"consumable insert":"vòng lót nóng chảy",

/* ---------- Các phần của mối hàn ---------- */
"weld metal":"kim loại mối hàn",
"parent metal":"kim loại cơ bản",
"base metal":"kim loại cơ bản",
"fusion zone":"vùng nóng chảy",
"fusion line":"đường chảy (ranh giới nóng chảy)",
"fusion boundary":"ranh giới nóng chảy",
"heat affected zone":"vùng ảnh hưởng nhiệt (HAZ)",
"haz":"vùng ảnh hưởng nhiệt",
"weld zone":"vùng hàn",
"weld face":"bề mặt mối hàn",
"weld root":"chân/đáy mối hàn",
"weld toe":"chân mối hàn (mép tiếp giáp bề mặt)",
"toe":"chân mối hàn (mép)",
"root":"đáy mối hàn",
"cap":"lớp phủ (lớp hoàn thiện mặt)",
"root run":"đường hàn đáy (lớp lót)",
"root pass":"đường hàn đáy",
"hot pass":"đường hàn nóng (lớp thứ 2 sau lớp đáy)",
"filler pass":"lớp hàn điền đầy",
"capping pass":"lớp hàn phủ mặt",
"run":"đường hàn (1 lượt hàn)",
"pass":"lượt hàn, đường hàn",
"layer":"lớp hàn",
"interpass":"giữa các lớp hàn",
"interrun":"giữa các đường hàn",
"weld width":"bề rộng mối hàn",
"excess weld metal":"kim loại đắp thừa (phần nhô mặt)",
"reinforcement":"phần đắp cao (kim loại thừa trên mặt)",
"root penetration":"độ ngấu đáy",
"excess penetration":"ngấu quá mức (đáy lồi quá)",
"design throat":"chiều cao tính toán (mối hàn góc)",
"actual throat":"chiều cao thực tế",
"throat thickness":"chiều cao mối hàn góc (throat)",
"leg length":"cạnh mối hàn góc",
"mitre fillet":"mối hàn góc phẳng đều 2 cạnh",
"concave":"lõm",
"convex":"lồi",
"deep penetration":"ngấu sâu",
"partial penetration":"ngấu một phần",
"full penetration":"ngấu hoàn toàn",
"dilution":"độ pha loãng (kim loại cơ bản hòa vào mối hàn)",

/* ---------- Tư thế hàn ---------- */
"welding position":"tư thế hàn",
"flat position":"tư thế hàn sấp (bằng)",
"horizontal":"tư thế hàn ngang",
"vertical up":"hàn leo (từ dưới lên)",
"vertical down":"hàn tụt (từ trên xuống)",
"overhead":"hàn trần (ngửa)",
"progression":"hướng hàn (lên/xuống)",
"inclined":"nghiêng",
"rotated":"quay (ống quay khi hàn)",
"fixed":"cố định (ống không quay)",

/* ---------- Khuyết tật hàn ---------- */
"defect":"khuyết tật (vượt mức cho phép, phải sửa)",
"imperfection":"bất liên tục (sai lệch, chưa chắc bị loại)",
"discontinuity":"bất liên tục",
"flaw":"khuyết tật, tật",
"crack":"nứt",
"solidification crack":"nứt kết tinh (nứt nóng)",
"hot crack":"nứt nóng",
"cold crack":"nứt nguội",
"hydrogen crack":"nứt do hydro (nứt nguội)",
"hydrogen induced cold cracking":"nứt nguội do hydro (HICC)",
"lamellar tearing":"nứt tách lớp (rách tầng)",
"crater crack":"nứt hõm cuối (nứt miệng hàn)",
"crater pipe":"lõm co ngót cuối đường hàn",
"centreline crack":"nứt giữa tâm mối hàn",
"transverse crack":"nứt ngang",
"longitudinal crack":"nứt dọc",
"toe crack":"nứt chân mối hàn",
"underbead crack":"nứt dưới lớp hàn (trong HAZ)",
"reheat crack":"nứt tái nhiệt (khi PWHT)",
"porosity":"rỗ khí",
"cluster porosity":"rỗ khí cụm",
"herringbone porosity":"rỗ khí xương cá",
"blowhole":"rỗ khí lớn",
"gas pore":"lỗ rỗ khí",
"wormhole":"rỗ ống (rỗ khí dạng ống dài)",
"surface breaking":"hở ra bề mặt",
"inclusion":"lẫn tạp chất (ngậm xỉ/tạp)",
"slag inclusion":"ngậm xỉ",
"tungsten inclusion":"ngậm vonfram",
"copper inclusion":"ngậm đồng",
"lack of fusion":"không ngấu (hàn không chảy dính)",
"lack of sidewall fusion":"không ngấu thành rãnh",
"lack of root fusion":"không ngấu đáy",
"lack of inter-run fusion":"không ngấu giữa các đường hàn",
"lack of penetration":"không thấu (đáy không ngấu hết)",
"incomplete penetration":"ngấu không hoàn toàn",
"incompletely filled groove":"rãnh hàn chưa điền đầy",
"undercut":"cháy chân (rãnh khuyết ở chân mối hàn)",
"underfill":"thiếu hụt bề mặt (chưa điền đầy)",
"overlap":"chờm phủ (kim loại tràn không ngấu lên bề mặt)",
"cold lap":"chờm nguội",
"spatter":"bắn tóe",
"arc strike":"vết mồi hồ quang (chạm que ngoài mối hàn)",
"stray arc":"hồ quang lạc",
"burn through":"cháy thủng",
"root concavity":"lõm đáy",
"root suck back":"hụt đáy (co lõm đáy)",
"shrinkage":"co ngót",
"shrinkage cavity":"lỗ co ngót",
"mechanical damage":"hư hại cơ học",
"chipping mark":"vết đục",
"grinding mark":"vết mài",
"distortion":"biến dạng",
"angular distortion":"biến dạng góc",
"residual stress":"ứng suất dư",
"restraint":"sự kìm hãm (độ cứng vững chống co ngót)",

/* ---------- Quy trình & thông số hàn ---------- */
"welding process":"quá trình hàn (phương pháp hàn)",
"mma":"hàn hồ quang tay (que hàn vỏ bọc, SMAW)",
"smaw":"hàn hồ quang tay que vỏ bọc",
"tig":"hàn TIG (điện cực vonfram, khí trơ)",
"gtaw":"hàn TIG",
"mig":"hàn MIG (dây hàn, khí trơ)",
"mag":"hàn MAG (dây hàn, khí hoạt tính)",
"gmaw":"hàn MIG/MAG",
"fcaw":"hàn dây lõi thuốc",
"flux cored":"dây lõi thuốc",
"saw":"hàn hồ quang chìm (dưới lớp thuốc)",
"submerged arc":"hồ quang chìm",
"electroslag":"hàn điện xỉ",
"arc":"hồ quang",
"arc length":"chiều dài hồ quang",
"arc voltage":"điện áp hồ quang",
"arc energy":"năng lượng hồ quang (kJ/mm)",
"heat input":"nhiệt lượng đưa vào (kJ/mm)",
"current":"dòng điện",
"amperage":"cường độ dòng điện (A)",
"voltage":"điện áp (V)",
"travel speed":"tốc độ hàn (tốc độ di chuyển)",
"polarity":"cực tính",
"dc":"dòng một chiều",
"ac":"dòng xoay chiều",
"dcep":"một chiều cực dương (điện cực nối +)",
"dcen":"một chiều cực âm (điện cực nối -)",
"electrode positive":"điện cực dương",
"electrode negative":"điện cực âm",
"open circuit voltage":"điện áp không tải (OCV)",
"ocv":"điện áp không tải",
"duty cycle":"chu kỳ tải (thời gian hàn cho phép trong 10 phút)",
"constant current":"đặc tính dòng không đổi (rơi)",
"constant voltage":"đặc tính áp không đổi (phẳng)",
"drooping characteristic":"đặc tính rơi (dòng không đổi)",
"flat characteristic":"đặc tính phẳng (áp không đổi)",
"self-adjusting arc":"hồ quang tự điều chỉnh (MIG/MAG)",
"dip transfer":"chuyển dịch ngắn mạch (giọt nhỏ, dòng thấp)",
"short circuit":"ngắn mạch",
"spray transfer":"chuyển dịch phun (dòng cao)",
"globular transfer":"chuyển dịch giọt lớn",
"pulsed":"xung",
"stick out":"phần dây nhô (khoảng dây chìa khỏi bép)",
"electrode extension":"phần nhô điện cực",
"contact tip":"bép hàn (ống tiếp điện)",
"nozzle":"chụp khí",
"wire feed speed":"tốc độ cấp dây",
"burn off rate":"tốc độ cháy dây",
"deposition rate":"tốc độ đắp",
"stringer bead":"đường hàn thẳng (không lắc)",
"weave":"lắc que (dao động ngang)",
"weaving":"kỹ thuật lắc que",
"technique":"kỹ thuật",
"run out length":"chiều dài đường hàn trên 1 que",
"tacking":"hàn đính",
"weld sequence":"trình tự hàn",
"balanced welding":"hàn cân bằng (giảm biến dạng)",
"back step":"hàn giật lùi",

/* ---------- Que hàn, dây hàn, khí, thuốc ---------- */
"consumable":"vật liệu hàn tiêu hao (que/dây/thuốc/khí)",
"electrode":"điện cực, que hàn",
"covered electrode":"que hàn vỏ bọc",
"coating":"vỏ bọc que hàn / lớp phủ",
"flux":"thuốc hàn",
"cellulosic":"vỏ bọc xenlulo (ngấu sâu, nhiều hydro)",
"rutile":"vỏ bọc rutil (dễ hàn, đa dụng)",
"basic":"vỏ bọc bazơ (hydro thấp, cơ tính cao)",
"low hydrogen":"hydro thấp",
"hydrogen controlled":"kiểm soát hydro",
"baking":"sấy khô (que bazơ, nhiệt cao)",
"drying":"sấy",
"quiver":"ống đựng que giữ nhiệt (mang theo người)",
"holding oven":"tủ giữ nhiệt que hàn",
"filler wire":"dây hàn phụ",
"filler metal":"kim loại điền đầy",
"shielding gas":"khí bảo vệ",
"inert gas":"khí trơ (argon, heli)",
"active gas":"khí hoạt tính (CO2, hỗn hợp có O2)",
"argon":"khí argon",
"helium":"khí heli",
"carbon dioxide":"khí CO2",
"gas flow rate":"lưu lượng khí",
"backing gas":"khí bảo vệ đáy (lót trong ống)",
"purging":"thổi khí đuổi (bảo vệ mặt sau)",
"tungsten electrode":"điện cực vonfram",
"thoriated":"vonfram pha thori",
"ceriated":"vonfram pha xeri",
"gas lens":"bộ chỉnh dòng khí (TIG)",
"batch":"lô (vật liệu)",
"batch certificate":"chứng chỉ lô",

/* ---------- Vật liệu & luyện kim ---------- */
"carbon steel":"thép cacbon",
"carbon manganese steel":"thép cacbon-mangan",
"low alloy steel":"thép hợp kim thấp",
"stainless steel":"thép không gỉ",
"austenitic":"austenit",
"ferritic":"ferit",
"martensitic":"mactenxit",
"duplex":"thép duplex (2 pha)",
"alloy":"hợp kim",
"alloying element":"nguyên tố hợp kim",
"carbon equivalent":"đương lượng cacbon (CEV)",
"cev":"đương lượng cacbon",
"hardenability":"tính tôi cứng (dễ tạo tổ chức cứng)",
"hardness":"độ cứng",
"microstructure":"tổ chức tế vi",
"grain":"hạt (tinh thể)",
"grain growth":"lớn hạt",
"grain refinement":"làm mịn hạt",
"solidification":"quá trình kết tinh (đông đặc)",
"segregation":"thiên tích (tạp chất dồn về giữa)",
"sulphur":"lưu huỳnh",
"phosphorus":"phốt pho",
"impurity":"tạp chất",
"lamination":"tách lớp trong thép cán",
"through thickness":"theo chiều dày",
"ductility":"độ dẻo",
"toughness":"độ dai (chống phá hủy giòn)",
"brittle":"giòn",
"brittle fracture":"phá hủy giòn",
"ductile fracture":"phá hủy dẻo",
"fatigue":"mỏi",
"fatigue crack":"nứt mỏi",
"tensile strength":"độ bền kéo",
"yield strength":"giới hạn chảy",
"elongation":"độ giãn dài",
"stress":"ứng suất",
"strain":"biến dạng (tương đối)",
"creep":"dão (biến dạng chậm ở nhiệt cao)",
"corrosion":"ăn mòn",
"weld decay":"ăn mòn vùng HAZ thép không gỉ",
"sensitisation":"nhạy hóa (mất crom ở biên hạt)",

/* ---------- Nhiệt luyện ---------- */
"preheat":"gia nhiệt trước khi hàn",
"preheating":"gia nhiệt sơ bộ",
"interpass temperature":"nhiệt độ giữa các lớp hàn",
"post weld heat treatment":"xử lý nhiệt sau hàn (PWHT)",
"pwht":"xử lý nhiệt sau hàn",
"stress relief":"khử ứng suất",
"annealing":"ủ",
"normalising":"thường hóa",
"quenching":"tôi",
"tempering":"ram",
"hardening":"tôi cứng",
"soak time":"thời gian giữ nhiệt",
"soaking temperature":"nhiệt độ giữ",
"heating rate":"tốc độ nâng nhiệt",
"cooling rate":"tốc độ nguội",
"thermocouple":"cặp nhiệt điện (đo nhiệt độ)",
"temperature indicating crayon":"bút chì nhiệt (đo nhiệt độ)",
"furnace":"lò nhiệt luyện",

/* ---------- Kiểm tra & NDT ---------- */
"visual inspection":"kiểm tra ngoại quan (bằng mắt)",
"visual examination":"kiểm tra bằng mắt",
"ndt":"kiểm tra không phá hủy",
"non-destructive testing":"kiểm tra không phá hủy",
"penetrant testing":"kiểm tra thẩm thấu (PT)",
"dye penetrant":"chất thẩm thấu màu",
"fluorescent penetrant":"chất thẩm thấu huỳnh quang",
"developer":"chất hiện (PT)",
"penetrant":"chất thẩm thấu",
"dwell time":"thời gian ngấm (PT)",
"magnetic particle":"kiểm tra bột từ (MT)",
"mpi":"kiểm tra bột từ",
"prod":"que châm điện (MT)",
"yoke":"gông từ",
"flux indication":"chỉ thị từ",
"demagnetise":"khử từ",
"radiography":"chụp ảnh phóng xạ (RT)",
"radiographic testing":"kiểm tra chụp phim (RT)",
"x-ray":"tia X",
"gamma ray":"tia gamma",
"iridium 192":"nguồn Iridi-192",
"film density":"độ đen phim",
"sensitivity":"độ nhạy",
"iqi":"chỉ thị chất lượng ảnh (Image Quality Indicator)",
"image quality indicator":"chỉ thị chất lượng ảnh (đo độ nhạy phim)",
"penetrameter":"IQI (tên gọi khác)",
"exposure":"chiếu chụp / liều chiếu",
"ultrasonic testing":"kiểm tra siêu âm (UT)",
"probe":"đầu dò",
"compression wave":"sóng dọc (sóng nén)",
"shear wave":"sóng ngang",
"couplant":"chất tiếp âm",
"calibration":"hiệu chuẩn",
"calibration block":"khối chuẩn",
"lamination check":"kiểm tra tách lớp",
"surface condition":"tình trạng bề mặt",
"planar defect":"khuyết tật phẳng (nứt, không ngấu)",
"volumetric defect":"khuyết tật khối (rỗ, ngậm xỉ)",
"indication":"chỉ thị (dấu hiệu phát hiện được)",
"relevant indication":"chỉ thị có nghĩa",
"false indication":"chỉ thị giả",
"evaluation":"đánh giá",
"interpretation":"giải đoán (phim, chỉ thị)",
"sentencing":"phán định (so chỉ thị với tiêu chí chấp nhận)",

/* ---------- Thử phá hủy ---------- */
"destructive testing":"thử phá hủy",
"mechanical testing":"thử cơ tính",
"tensile test":"thử kéo",
"transverse tensile":"thử kéo ngang mối hàn",
"all-weld tensile":"thử kéo toàn kim loại hàn",
"bend test":"thử uốn",
"root bend":"uốn đáy",
"face bend":"uốn mặt",
"side bend":"uốn cạnh",
"former":"gối uốn",
"charpy":"thử va đập Charpy",
"impact test":"thử va đập",
"charpy v-notch":"mẫu Charpy rãnh chữ V",
"notch":"rãnh khía (mẫu thử)",
"test temperature":"nhiệt độ thử",
"transition temperature":"nhiệt độ chuyển tiếp dẻo-giòn",
"upper shelf":"vùng năng lượng cao (dẻo)",
"lower shelf":"vùng năng lượng thấp (giòn)",
"hardness test":"thử độ cứng",
"vickers":"độ cứng Vickers (HV)",
"rockwell":"độ cứng Rockwell",
"brinell":"độ cứng Brinell",
"macro examination":"soi thô đại (mặt cắt mối hàn)",
"micro examination":"soi tế vi",
"fracture test":"thử phá gãy",
"nick break":"thử bẻ gãy có khía",
"fillet fracture":"thử phá gãy mối hàn góc",
"specimen":"mẫu thử",
"test piece":"phôi thử / mẫu thử",
"coupon":"phôi hàn thử",

/* ---------- Ký hiệu hàn & bản vẽ ---------- */
"welding symbol":"ký hiệu hàn",
"arrow side":"phía mũi tên",
"other side":"phía bên kia",
"reference line":"đường chuẩn (ký hiệu hàn)",
"tail":"đuôi ký hiệu (ghi chú quy trình)",
"weld all round":"hàn vòng quanh chu vi",
"field weld":"hàn tại công trường",
"site weld":"hàn tại hiện trường",
"drawing":"bản vẽ",
"dimension":"kích thước",
"tolerance":"dung sai",
"intermittent weld":"hàn ngắt quãng (hàn cách đoạn)",
"staggered":"so le",
"pitch":"bước (khoảng cách tâm-tâm)",

/* ---------- Đo kiểm mối hàn ---------- */
"gauge":"dưỡng đo, thước đo",
"weld gauge":"dưỡng đo mối hàn",
"fillet gauge":"dưỡng đo mối hàn góc",
"depth gauge":"thước đo chiều sâu",
"linear misalignment":"lệch mép thẳng (hi-lo)",
"angular misalignment":"lệch góc",
"peaking":"gồ đỉnh (ống méo tại mối hàn dọc)",
"ovality":"độ ô van",
"straightness":"độ thẳng",
"profile":"biên dạng (hình dạng bề mặt)",
"blend":"chuyển tiếp mượt (chân mối hàn)",
"toe blend":"độ mượt chân mối hàn",

/* ---------- Cắt, dũi, sửa ---------- */
"oxy-fuel cutting":"cắt khí oxy-nhiên liệu",
"oxyacetylene":"oxy-axetylen",
"flame cutting":"cắt bằng ngọn lửa khí",
"kerf":"rãnh cắt",
"drag lines":"vệt cắt (trên mặt cắt)",
"gouging":"dũi (moi rãnh)",
"arc air gouging":"dũi hồ quang khí nén (carbon)",
"grinding":"mài",
"repair":"sửa chữa",
"excavation":"moi khuyết tật (đào bỏ)",
"rectification":"khắc phục, sửa lại",
"dressing":"mài sửa bề mặt",

/* ---------- An toàn ---------- */
"safety":"an toàn",
"arc eye":"đau mắt hàn (viêm giác mạc do tia hồ quang)",
"ultraviolet":"tia cực tím (UV)",
"radiation":"bức xạ",
"fume":"khói hàn",
"ventilation":"thông gió",
"electric shock":"điện giật",
"ppe":"trang bị bảo hộ cá nhân",
"earth":"nối đất",
"confined space":"không gian kín",
"permit to work":"giấy phép làm việc",
"fire watch":"người canh lửa",

/* ---------- Từ hay gặp trong đề thi ---------- */
"which of the following":"cái nào sau đây",
"most likely":"nhiều khả năng nhất",
"least likely":"ít khả năng nhất",
"refer to":"tham chiếu đến, xem",
"in accordance with":"theo đúng, phù hợp với",
"with reference to":"tham chiếu theo",
"prior to":"trước khi",
"subsequent":"sau đó, tiếp theo",
"mandatory":"bắt buộc",
"essential variable":"biến số thiết yếu (đổi là phải chứng nhận lại WPS)",
"non-essential variable":"biến số không thiết yếu",
"range of approval":"phạm vi phê duyệt",
"extent of testing":"khối lượng/mức độ kiểm tra",
"susceptible":"dễ bị, nhạy cảm với",
"minimise":"giảm thiểu",
"eliminate":"loại bỏ",
"assess":"đánh giá",
"verify":"xác nhận, kiểm chứng",
"ensure":"đảm bảo",
"require":"yêu cầu",
"reject":"loại bỏ, không chấp nhận",
"accept":"chấp nhận",
"applicable":"áp dụng được, hiện hành",
"statement":"phát biểu, câu nhận định",
"true":"đúng",
"false":"sai",
"cause":"nguyên nhân, gây ra",
"prevent":"ngăn ngừa",
"avoid":"tránh",
"reduce":"giảm",
"increase":"tăng",
"decrease":"giảm",
"excessive":"quá mức",
"insufficient":"không đủ, thiếu",
"adjacent":"kề bên, lân cận",
"longitudinal":"theo chiều dọc",
"transverse":"theo chiều ngang",
"circumferential":"theo chu vi (mối hàn vòng ống)",
"seam":"mối hàn dọc (thân ống/bồn)",
"pipe":"ống",
"plate":"tấm",
"thickness":"chiều dày",
"diameter":"đường kính",
"outside diameter":"đường kính ngoài",
"wall thickness":"chiều dày thành ống",
"material":"vật liệu",
"property":"tính chất",
"mechanical properties":"cơ tính",
"composition":"thành phần hóa học",
"contamination":"nhiễm bẩn",
"moisture":"hơi ẩm",
"hygroscopic":"hút ẩm",
"atmosphere":"môi trường khí quyển",
"ambient temperature":"nhiệt độ môi trường",
"solidify":"đông đặc, kết tinh",
"molten":"nóng chảy",
"weld pool":"vũng hàn",
"deposit":"đắp (kim loại hàn)",
"fabrication":"chế tạo (kết cấu)",
"erection":"lắp dựng",
"commissioning":"chạy thử nghiệm thu",
"service condition":"điều kiện vận hành",
"in service":"đang vận hành",
"pressure test":"thử áp lực",
"hydrostatic test":"thử thủy tĩnh (thử nước)",
"pneumatic test":"thử khí nén",
"leak test":"thử rò rỉ"
};
