/* ============================================================
   THI BANK 6 — Bộ 199 câu hỏi–đáp truyền miệng (Cấp 2.3)
   Nguồn: "Tài liệu cấp 2.3.pdf" (Question & Answer Sheet)
   Đã sửa lỗi chính tả tiếng Anh; câu trùng lặp được gộp và ghi chú.
   ============================================================ */
window.THI_C23 = {id:'c23', icon:'📚', vi:'Bộ 199 câu hỏi–đáp (Cấp 2.3)', en:'199 Q&A sheet', type:'card', items:[
{q:'H-L045 test specimen: which position for hardness test?', a:'PE (hardness, macro)', vq:'Mẫu H-L045: thử độ cứng ở vị trí nào?', va:'PE — heat input thấp nhất nên cứng nhất.'},
{q:'What is the cost of weld repair?', a:'10 times the original weld', vq:'Chi phí sửa mối hàn?', va:'Gấp 10 lần hàn mới.'},
{q:'Which microstructure leads to H2 cracking?', a:'Microstructure > 400HV (martensite)', vq:'Tổ chức nào gây nứt hydro?', va:'MARTENSITE cứng >400HV.'},
{q:'SAW welding mechanism?', a:'Fully automatic (mechanised)', vq:'SAW vận hành kiểu gì?', va:'Tự động hoàn toàn — dây + thuốc cấp máy, xe tự chạy.'},
{q:'What is the purpose of a diesel generator (welding plant)?', a:'Preferred for site work (no mains power)', vq:'Máy phát diesel dùng khi nào?', va:'Hàn công trường xa lưới điện.'},
{q:'What is the effect of high voltage?', a:'Arc length ↑, weld width ↑, penetration ↓, amps ↓', vq:'Điện áp cao gây gì?', va:'Hồ quang dài, mối rộng, ngấu giảm — kèm rỗ khí, bắn tóe.'},
{q:'What is the purpose of a strong back?', a:'Prevent angular distortion in plates; prevent peaking in cylindrical shells', vq:'Strong back để làm gì?', va:'Gông giữ chống BIẾN DẠNG GÓC / chống "gãy đỉnh" khi hàn vỏ trụ.'},
{q:'What defect is not detected in RT?', a:'Planar defects (cracks, LOF)', vq:'RT không phát hiện gì?', va:'Khuyết tật PHẲNG — không đổi mật độ xuyên tia.'},
{q:'What is the purpose of inductance? What happens if too high / too low?', a:'Reduce spatter. Too high → lack of fusion & stubbing; too low → spatter', vq:'Điện cảm để làm gì?', va:'Làm mượt dòng đoản mạch → ít bắn tóe. Cao quá: dính que/LOF; thấp quá: bắn tóe.'},
{q:'What happens when polarity changes from DC+ to DC-?', a:'Weld width increases, penetration decreases', vq:'DC+ → DC-?', va:'Ngấu giảm, mối rộng/đắp hơn (nhiệt về que).'},
{q:'Which process for high deposition rate welds?', a:'SAW', vq:'Đắp cao nhất?', va:'SAW — dòng cực lớn, K=1. (Site + PF thì FCAW.)'},
{q:'What is most likely to solidification crack?', a:'SAW & austenitic stainless steel', vq:'Cái gì dễ nứt đông đặc?', va:'SAW (bể hàn to, hình dạng sâu-hẹp) & inox austenit (S, P, co ngót lớn).'},
{q:'What is the angle for a J-groove?', a:'10–15° (notes say 12–15°)', vq:'Góc mép J?', va:'Nhỏ (10–15°) vì đã có bán kính chân.'},
{q:'At which temperature does oxy-fuel cutting happen & what reaction?', a:'~850°C (ignition 700–960°C); exothermic reaction', vq:'Nhiệt độ & phản ứng cắt oxy?', va:'Sắt bắt cháy ~850°C — phản ứng TỎA NHIỆT, dưới điểm nóng chảy.'},
{q:'COSHH stands for?', a:'Control Of Substances Hazardous to Health', vq:'COSHH?', va:'Luật kiểm soát chất độc hại với sức khỏe (UK).'},
{q:'What is the purpose of a transformer? And a rectifier?', a:'Transformer: AC→AC (drop voltage, raise current); Rectifier: AC→DC', vq:'Biến áp & chỉnh lưu?', va:'Biến áp hạ áp tăng dòng; chỉnh lưu đổi AC thành DC.'},
{q:'If carbon steel is changed to 316L, what defect can occur?', a:'Solidification cracking (per this sheet)', vq:'Đổi thép C → 316L dễ bị gì?', va:'Bộ 2.3 chọn NỨT ĐÔNG ĐẶC (austenit + tạp chất). Bộ 2.1 chọn weld decay — đọc kỹ lựa chọn đề.', n:'Câu có 2 trường phái đáp án.'},
{q:'For checking thickness, which NDT method?', a:'UT (0° compression probe)', vq:'Đo chiều dày dùng gì?', va:'Siêu âm đầu dò thẳng 0°.'},
{q:'Principle of MPI?', a:'Magnetic flux leakage & magnetic particles', vq:'Nguyên lý MPI?', va:'Rò rỉ từ thông hút bột từ tụ tại khuyết tật.'},
{q:'To weld 2-inch OD, 5mm thick pipe — which transfer mode in MIG/MAG?', a:'Dip transfer', vq:'Ống nhỏ 5mm hàn MIG kiểu gì?', va:'DIP — mỏng + mọi tư thế.'},
{q:'In all-weld tensile, what will not be measured?', a:'Rp', vq:'Thử kéo C-Mn không đo?', va:'Rp chỉ cho vật liệu không có điểm chảy rõ.'},
{q:'Oxy-fuel cutting is used on which materials?', a:'Carbon steel & low alloy steel', vq:'Cắt oxy dùng cho gì?', va:'Chỉ thép C & hợp kim thấp (oxit chảy dễ). Inox/nhôm phải plasma.'},
{q:'When will Rp be measured?', a:'When the material has no defined yield point (very ductile / SS, Al)', vq:'Khi nào đo Rp?', va:'Vật liệu không có điểm chảy rõ → Rp0,2.'},
{q:'In SAW process heat input is max — why?', a:'Arc is insulated (under flux); uses very high current (1000A+)', vq:'Vì sao SAW HI lớn nhất?', va:'Hồ quang chìm không mất nhiệt + dòng cực lớn.'},
{q:'Why does porosity occur?', a:'Damp or contaminated electrode (also long arc/high V, lack of gas)', vq:'Vì sao rỗ khí?', va:'Que ẩm/bẩn, hồ quang dài, thiếu khí bảo vệ.'},
{q:'What is undercut & why?', a:'Melting of top edge due to high current or high travel speed', vq:'Undercut là gì?', va:'Rãnh khuyết ở chân/mép mối do dòng cao + đi nhanh.'},
{q:'Where does solidification cracking occur?', a:'Centre line of weld metal', vq:'Nứt đông đặc nằm ở đâu?', va:'GIỮA TÂM mối hàn — nơi đông đặc cuối cùng, tạp chất dồn về.'},
{q:'Where does weld decay occur?', a:'HAZ', vq:'Weld decay ở đâu?', va:'Vùng HAZ bị nung 600–850°C (sensitisation).'},
{q:'Flames of oxy-fuel gas cutting?', a:'Neutral, oxidising, carburising', vq:'3 loại ngọn lửa?', va:'Trung tính (cắt thép C), oxy hóa (đồng thau), carbua hóa (nhiều gas).'},
{q:'What is the polarity of MIG/MAG?', a:'DC+ (DCEP)', vq:'MIG/MAG dùng cực gì?', va:'DCEP — hồ quang ổn định, ngấu tốt.'},
{q:'Why is AC current used in the TIG process?', a:'To remove the oxide layer (aluminium)', vq:'TIG dùng AC khi nào?', va:'Hàn nhôm/magiê — phá oxit bằng nửa chu kỳ dương.'},
{q:'In which DT is welder qualification done?', a:'Fracture and macro (fillet); bend & macro (butt)', vq:'WQT thử gì?', va:'Định tính: bẻ gãy/uốn + macro.'},
{q:'Why is a vertex angle used in the TIG process?', a:'Best penetration (focused arc)', vq:'Mài góc đỉnh TIG để làm gì?', va:'Hồ quang tập trung → ngấu sâu, bead gọn.'},
{q:'What is the transition range of Charpy V-notch (C-Mn)?', a:'0 to -20°C ductile; -20 to -30°C brittle (per sheet)', vq:'Vùng chuyển tiếp Charpy?', va:'Theo bộ đề: 0…-20°C còn dai; -20…-30°C giòn. Bản chất: dải chuyển tiếp dẻo-giòn của thép C-Mn.'},
{q:'In which weld preparation is a root radius pre-set?', a:'J or U', vq:'Mép nào có bán kính chân?', va:'J và U (gia công máy).'},
{q:'A welder qualifies in all positions except vertical down — which progression is this?', a:'Uphill — PF', vq:'Đậu mọi tư thế trừ hàn xuống → progression?', va:'UPHILL (PF). Câu quan trọng — đề hay hỏi!'},
{q:'As per AWS A5.1: 7018, 8018 — which type of electrode?', a:'Basic (low hydrogen)', vq:'7018/8018 là loại que?', va:'Đuôi 8 = bazơ + bột sắt.'},
{q:'In TIG welding, what are the different electrode tip shapes?', a:'Pointed (vertex) for DCEN — deep pen; balled end for AC; flat end not recommended', vq:'Các dạng đầu điện cực TIG?', va:'Nhọn (thoriated/ceriated/lanthanated) cho DC-; tròn (zirconiated) cho AC.'},
{q:'What is the gas flow rate of TIG welding?', a:'10–12 L/min (8–12)', vq:'Lưu lượng khí TIG?', va:'8–12 L/phút.'},
{q:'About the pulse transfer technique?', a:'V<24V eq., all positions, moderate heat input, welds >6mm, pulse current pinch effect', vq:'Pulse transfer?', va:'Xung dòng bóp giọt (pinch) — mọi tư thế, ít bắn tóe, HI vừa.'},
{q:'What is the purpose of post-flow (TIG)?', a:'To avoid weld pool contamination (protect cooling weld & electrode)', vq:'Khí post-flow để làm gì?', va:'Che mối + điện cực đang nguội khỏi oxy hóa sau khi tắt hồ quang.'},
{q:'Composition of MIG/MAG shielding gases?', a:'MIG: Ar/He (spray, pulse). MAG: 100% CO2 (dip); Ar+15–20% CO2 (spray/pulse); Ar+1–5% O2/CO2 for SS', vq:'Khí MIG/MAG?', va:'MIG=trơ (Ar/He); MAG=hoạt tính (CO₂, hỗn hợp Ar+CO₂/O₂).'},
{q:'What is the CTWD?', a:'Contact Tip to Work Distance', vq:'CTWD?', va:'Khoảng cách bép tiếp điện → vật hàn (ảnh hưởng dòng & stickout).'},
{q:'About globular transfer?', a:'Lots of spatter; only PA position; ~100% CO2; 3–6mm thickness', vq:'Globular transfer?', va:'Giọt to hơn dây, rơi tự do → bắn tóe nhiều, chỉ hàn sấp.'},
{q:'What is the thermal efficiency factor of SAW?', a:'1.0 — arc energy equals heat input', vq:'Hệ số K của SAW?', va:'K=1,0.'},
{q:'Various factors to avoid distortion?', a:'Reduce number of runs, balanced welding, reduce weld metal, back-to-back assembly, minimise welding time', vq:'Cách giảm biến dạng?', va:'Ít đường hàn, hàn cân xứng, ít kim loại đắp, kẹp lưng-đối-lưng, hàn nhanh.'},
{q:'About Vickers hardness?', a:'Square-based diamond pyramid indenter; HV5, HV10, HV25', vq:'Đo cứng Vickers?', va:'Mũi kim cương chóp vuông; tải 5/10/25kg — chuẩn cho mối hàn.'},
{q:'What happens if preheat is decreased?', a:'Faster cooling, shrinkage stress, moisture not removed, hardened microstructure risk, hydrogen not diffused', vq:'Giảm preheat?', va:'Nguội nhanh → cứng, giữ ẩm, giữ hydro → nguy cơ HICC.'},
{q:'What is HF (high frequency) start?', a:'Initiates TIG arc without touching; ~20,000V pulses; can damage electronics', vq:'Mồi HF?', va:'Mồi không chạm (sạch) nhưng gây nhiễu điện từ.'},
{q:'What is soak time (PWHT)?', a:'Time held at peak temperature: 1 hour per 25.4mm (1 inch) of thickness', vq:'Soak time?', va:'Giữ nhiệt 1 giờ cho mỗi 25mm chiều dày.'},
{q:'Arc-air gouging is used on which materials?', a:'Both ferrous and non-ferrous', vq:'Thổi hồ quang carbon dùng cho?', va:'Cả kim loại đen & màu (DCEP + khí nén).'},
{q:'About SAW welding?', a:'High heat input, fully mechanised, high productivity, PA & PB positions only', vq:'Đặc điểm SAW?', va:'HI cao, tự động, năng suất lớn, CHỈ hàn sấp/ngang máng.'},
{q:'What is an RCD?', a:'Residual Current Device — protects from electric shock due to residual/leakage current', vq:'RCD là gì?', va:'Thiết bị chống giật do dòng rò.'},
{q:'What are the effects of cadmium?', a:'Toxic fumes — metal fume fever; ~20 min welding near cadmium can be fatal', vq:'Cadimi nguy hiểm thế nào?', va:'Khói Cd cực độc — hàn/cắt vật mạ Cd có thể tử vong.'},
{q:'Overlap/cold lap is seen by which examination?', a:'Macroscopic examination (visual/macro)', vq:'Cold lap thấy bằng gì?', va:'Quan sát macro/VT — kim loại tràn không ngấu ở chân mối.'},
{q:'In welding, what happens to the HAZ?', a:'Strength changes, loss of corrosion resistance, cracking risk, lower toughness, higher hardness', vq:'HAZ thay đổi gì?', va:'Vùng bị ảnh hưởng nhiệt: cứng lên, dai giảm, dễ nứt/ăn mòn.'},
{q:'What is a compound weld?', a:'Two different types of weld in one joint (e.g. butt + fillet)', vq:'Compound weld?', va:'Mối TỔ HỢP giáp mép + góc — cần preheat cao nhất.'},
{q:'What happens when root face increases?', a:'Lack of root penetration', vq:'Root face tăng?', va:'Thiếu ngấu chân.'},
{q:'What happens if changing V to J prep?', a:'Groove angle reduces — less filler, but access more difficult; machining needed', vq:'Đổi V sang J?', va:'Ít kim loại đắp, ít biến dạng nhưng phải gia công máy, thao tác khó hơn.'},
{q:'How to avoid crater (pipe)?', a:'Use slope-out (crater fill) device', vq:'Tránh lõm cuối mối?', va:'Dùng chức năng giảm dòng cuối (slope-out/crater fill).'},
{q:'About arc strikes?', a:'Local damage adjacent to weld → hard HAZ → serious cracking risk; repaired by grinding (+check)', vq:'Arc strike?', va:'Vết mồi hồ quang tạo vùng tôi cứng → mài bỏ + kiểm tra.'},
{q:'What is a pWPS?', a:'Preliminary WPS — used for the qualification test to produce the WPQR', vq:'pWPS?', va:'WPS sơ bộ để hàn mẫu qualify → ra WPQR → duyệt thành WPS.'},
{q:'What are the responsibilities of a welding inspector?', a:'Inspect before, during and after welding; ensure all welding activities comply with the specification', vq:'Trách nhiệm inspector?', va:'Đảm bảo mọi hoạt động hàn ĐÚNG SPEC — trước/trong/sau hàn.'},
{q:'What is the temperature of quenching & tempering?', a:'Tempering ~550–650°C', vq:'Nhiệt độ ram?', va:'550–650°C (dưới đường A1) — giảm giòn sau tôi.'},
{q:'Duty before welding?', a:'Check preheat, check consumables (and documents, fit-up)', vq:'Trước khi hàn kiểm gì?', va:'Preheat, que/dây đúng chủng loại & sấy, hồ sơ, gá lắp.'},
{q:'Lamellar tearing occurs in?', a:'Parent metal (through-thickness direction)', vq:'Xé lớp xảy ra ở đâu?', va:'KIM LOẠI NỀN — theo chiều dày tấm, dạng bậc thang.'},
{q:'Which joint profile has the greatest fatigue life?', a:'Concave (smooth toe blend)', vq:'Biên dạng nào chịu mỏi tốt nhất?', va:'Mối hơi LÕM, chân mối mượt → ít tập trung ứng suất.'},
{q:'Pre-flow in TIG is used for?', a:'Purge the torch/protect at arc start', vq:'Pre-flow?', va:'Xả khí trước khi mồi — đuổi không khí trong ống & chụp khí.'},
{q:'A welder welding in PG — suitable electrode? Name?', a:'E6010 — cellulosic', vq:'Que hàn PG?', va:'Cellulosic — chuyên hàn xuống.'},
{q:'Lack of fusion in which position in MAG welding? Reason?', a:'PG — weld pool flows ahead due to gravity', vq:'MAG vị trí nào dễ LOF?', va:'PG — bể hàn trôi TRƯỚC hồ quang làm lớp đệm.'},
{q:'Hardness sample from H-L045 fixed pipe (downhill)? Why?', a:'PE — low heat input', vq:'Mẫu độ cứng H-L045?', va:'PE, HI thấp nhất → cứng nhất.'},
{q:'Charpy V-notch samples are taken from? Why?', a:'PF — high heat input', vq:'Mẫu Charpy lấy ở?', va:'PF, HI cao nhất → độ dai kém nhất.'},
{q:'Hardness of material increased by?', a:'Fast cooling / increased carbon (low heat input)', vq:'Độ cứng tăng do?', va:'Nguội nhanh + %C cao (+CEV cao).'},
{q:'What is the use of a transformer? Why?', a:'Drop voltage & raise current for welding; smooths current surges', vq:'(Ôn) Biến áp?', va:'Hạ áp 380/220→20-100V, tăng dòng 50-500A.'},
{q:'In which profile does decreased fatigue life occur?', a:'Convex (sharp toe angle)', vq:'Biên dạng giảm tuổi thọ mỏi?', va:'Mối LỒI — góc chân gắt → tập trung ứng suất.'},
{q:'Which preparation has a land (root face) and small angle?', a:'J (5–15°)', vq:'Mép có land + góc nhỏ?', va:'Chữ J.'},
{q:'Design throat thickness formula?', a:'a = 0.707 × z; z = 1.41 × a', vq:'Công thức throat?', va:'Nhân 0,707 (hoặc 0,7 khi thi).'},
{q:'Which fillet weld shape has high strength (throat > design)?', a:'Convex has extra metal but design throat governs; concave gives best fatigue', vq:'Mối góc nào "khỏe"?', va:'Đắp lồi không tăng độ bền thiết kế (a tính theo mitre); lõm tốt cho mỏi. Đề 2.3 ghi "convex".', n:'Ghi chú gốc chọn convex — hiểu bản chất: độ bền do throat quyết định.'},
{q:'Preheat is most needed for which joints?', a:'Compound joint & tee joint', vq:'Mối nào cần preheat nhất?', va:'Tổ hợp & chữ T — nhiều đường thoát nhiệt.'},
{q:'About weaving?', a:'High heat input, low ductility/toughness, decreased hardness', vq:'Lắc que ảnh hưởng?', va:'HI tăng → mềm hơn nhưng dai giảm, HAZ rộng.'},
{q:'About solidification cracking (elements)?', a:'Sulphur, phosphorus (low-melting films)', vq:'Nứt đông đặc do nguyên tố nào?', va:'S & P tạo màng lỏng điểm chảy thấp giữa tâm mối.'},
{q:'About lamellar tearing (material property)?', a:'Poor through-thickness ductility — STRA < 20%', vq:'Xé lớp liên quan chỉ số nào?', va:'STRA (Short Transverse Reduction in Area) <20% = nhạy cảm; >20% an toàn.'},
{q:'Specimen taken from which position for toughness test?', a:'PF', vq:'Mẫu toughness ở đâu?', va:'PF — HI cao nhất.'},
{q:'About arc strike effects?', a:'Hard and brittle spot, area reduction, chance of cracking', vq:'Hậu quả arc strike?', va:'Điểm cứng giòn → khởi phát nứt.'},
{q:'About spatter and inductance?', a:'Too high inductance → lack of fusion; too low → spatter', vq:'(Ôn) Inductance?', va:'Thấp → bắn tóe; cao quá → LOF/dính.'},
{q:'Examples of qualitative & quantitative tests?', a:'Qualitative: bend, nick-break, macro. Quantitative: tensile, hardness, Charpy, CTOD', vq:'(Ôn) Định tính/định lượng?', va:'Định tính = đạt/rớt; định lượng = con số.'},
{q:'About UTS?', a:'Ultimate Tensile Strength = max load / CSA (N/mm²)', vq:'UTS?', va:'Độ bền kéo = lực max chia tiết diện.'},
{q:'Elongation formula?', a:'(Final length - original)/original × 100% (sheet: actual/original ×100)', vq:'Độ giãn dài?', va:'A% = ΔL/L₀ × 100 (đo trên gauge length).'},
{q:'Transition range in Charpy test?', a:'0 to -20°C ductile; -20 to -30°C brittle (C-Mn, per sheet)', vq:'(Ôn) Vùng chuyển tiếp?', va:'Dải dẻo→giòn khi nhiệt độ giảm.'},
{q:'About CTOD?', a:'Fracture toughness test; measures material property with pre-cracked specimen, slow loading', vq:'CTOD?', va:'Thử độ dai phá hủy — mẫu nứt mồi, tải chậm.'},
{q:'About the RT test — materials?', a:'Applicable to all materials', vq:'RT dùng cho vật liệu nào?', va:'Mọi vật liệu (cả không nhiễm từ).'},
{q:'On SS, which NDT methods are used?', a:'PT & RT', vq:'(Ôn) NDT cho inox?', va:'PT bề mặt + RT bên trong.'},
{q:'Laminations are checked with which probe?', a:'0° compression probe', vq:'Tách lớp (lamination) dò bằng gì?', va:'Đầu dò thẳng 0° — quét chiều dày tấm.'},
{q:'About +25% high heat input & -25% low heat input?', a:'+25% allowed when impact required; -25% when hardness requirement', vq:'Quy tắc ±25% HI?', va:'Impact → giới hạn TRÊN +25%; hardness → giới hạn DƯỚI -25%.'},
{q:'What is the essential variable for welder qualification?', a:'Welding position (among others: process, material group, thickness)', vq:'Biến thiết yếu của WQT?', va:'TƯ THẾ hàn là biến thiết yếu điển hình cho thợ.'},
{q:'Alloying elements and their effects?', a:'C-strength; Mn-toughness; Si-deoxidiser; Al-grain refiner; Cr-corrosion resistance; Mo-creep resistance; V-strength; Ni-low temperature toughness', vq:'Tác dụng nguyên tố hợp kim?', va:'C bền; Mn dai; Si khử oxy; Al mịn hạt; Cr chống gỉ; Mo chống rão; V bền; Ni dai lạnh. HỌC THUỘC!'},
{q:'About OCV range?', a:'50–90V', vq:'OCV?', va:'Điện áp không tải 50–90V (mồi hồ quang, an toàn).'},
{q:'In which electrode does fluid slag come?', a:'Basic (7018)', vq:'Que nào xỉ loãng?', va:'Bazơ — xỉ CaF₂ loãng, khó thao tác.'},
{q:'Purpose of vertex angle?', a:'Good penetration and profile', vq:'(Ôn) Góc đỉnh TIG?', va:'Ngấu sâu, hồ quang gọn.'},
{q:'About HAZ full details?', a:'SGRPT: Solidified weld – Grain growth – Recrystallised – Partially transformed – Tempered', vq:'Chuỗi HAZ?', va:'Nhớ "SGRPT" từ mối hàn ra ngoài.'},
{q:'If welder changes spray to dip transfer, what happens?', a:'Low penetration, high spatter, lack of fusion', vq:'(Ôn) Spray→dip?', va:'Ngấu giảm + bắn tóe + LOF.'},
{q:'If shielding gas changes from argon to helium (same settings)?', a:'Per sheet: low penetration (He needs higher flow/settings); hotter arc if adjusted', vq:'Ar → He?', va:'Ghi chú 2.3: ngấu giảm (nếu giữ nguyên thông số vì He cần lưu lượng/điện áp cao hơn). Các đề khác: hồ quang nóng hơn. Đọc kỹ câu hỏi!', n:'2 cách hỏi — cùng thông số thì ngấu giảm; chỉnh đúng thì hồ quang nóng hơn.'},
{q:'If arc voltage increases, which defect will come?', a:'Porosity', vq:'Điện áp cao → lỗi gì?', va:'Hồ quang dài → mất che chắn → rỗ khí.'},
{q:'Classification of electrode E7018?', a:'70 = tensile strength (ksi); 1 = all positions; 8 = flux coating type (basic + iron powder)', vq:'Giải mã E7018?', va:'70=UTS 70ksi; 1=mọi tư thế; 8=bazơ+bột sắt.'},
{q:'Difference between agglomerated flux & fused flux (SAW)?', a:'Agglomerated: can add alloys, but hygroscopic — needs baking; Fused: non-hygroscopic, lower quality additions', vq:'Thuốc thiêu kết vs nung chảy?', va:'THIÊU KẾT (agglomerated): thêm được hợp kim, HÚT ẨM phải sấy. NUNG CHẢY (fused): không hút ẩm, không thêm được hợp kim.', n:'Ghi chú 2.3 viết ngược — bản đúng: agglomerated hút ẩm, fused không hút ẩm.'},
{q:'What are the 4 factors of hydrogen cracking?', a:'H2 >15ml/100g; stress >0.5 YS; temperature <300°C; hardness >350-400HV', vq:'(Ôn) 4 yếu tố HICC?', va:'Hydro + ứng suất + nhiệt thấp + tổ chức cứng.'},
{q:'In a 10mm plate, preheat is checked at what distance?', a:'4×t = 40mm from the joint', vq:'Preheat đo cách mối?', va:'4×t (max 50mm); t>50 → 75mm.'},
{q:'What happens if a welder works 20 minutes in cadmium fumes?', a:'Fatality — death risk', vq:'20 phút trong khói cadimi?', va:'Có thể TỬ VONG — Cd cực độc.'},
{q:'What is the validity of equipment (calibration)?', a:'6 months', vq:'Hiệu lực hiệu chuẩn thiết bị?', va:'6 tháng (ampe kìm, đồng hồ...).'},
{q:'Preheat related to thickness — typical trigger?', a:'Combined thickness / >20mm with CEV consideration', vq:'Chiều dày & preheat?', va:'Tấm càng dày (tổng chiều dày các đường thoát nhiệt) càng cần preheat.'},
{q:'Essential variable for WPS?', a:'Anything affecting mechanical properties (process, HI, material, thickness, preheat, PWHT...)', vq:'Biến thiết yếu WPS?', va:'Thay đổi làm ẢNH HƯỞNG CƠ TÍNH → phải qualify lại.'},
{q:'Which process for high deposition + site welding?', a:'FCAW (136)', vq:'Đắp cao + công trường?', va:'FCAW — dây lõi thuốc.'},
{q:'Most solidification cracking occurs in which process?', a:'SAW (deep narrow bead, high dilution)', vq:'Quá trình dễ nứt đông đặc?', va:'SAW — bể hàn sâu hẹp, tỉ lệ D/W lớn.'},
{q:'Design throat & actual throat relation — which shape?', a:'Convex: actual > design', vq:'Cổ thực > cổ thiết kế khi nào?', va:'Mối LỒI (convex).'},
{q:'Can we use AC with the MMA process?', a:'Yes for suitable electrodes — minimises arc blow; not all electrodes run on AC', vq:'MMA dùng AC được không?', va:'Được với que phù hợp (rutile...); AC GIẢM THỔI LỆCH HỒ QUANG (arc blow).'},
{q:'Welding variables of MMA?', a:'Current, voltage, travel speed, polarity, type of electrode', vq:'Biến số MMA?', va:'Dòng, áp, tốc độ, cực tính, loại que.'},
{q:'BS EN E50 3 B — what does the 3 indicate? The 50?', a:'3 = toughness (47J at -30°C); 50 = yield strength 500 MPa', vq:'E50 3 B?', va:'50=YS 500MPa; 3=va đập -30°C; B=bazơ.'},
{q:'Why use the TIG process for aluminium (AC)?', a:'Cathodic cleaning', vq:'(Ôn) TIG nhôm?', va:'AC làm sạch oxit.'},
{q:'What is the undesirable element in solidification cracking?', a:'Sulphur', vq:'Nguyên tố hại nhất gây nứt nóng?', va:'LƯU HUỲNH (FeS màng lỏng).'},
{q:'How to avoid solidification cracks?', a:'Use Mn-based electrode/filler (Mn:S ratio), reduce dilution, clean joint', vq:'Tránh nứt đông đặc?', va:'Tăng Mn (tạo MnS), giảm pha loãng, sạch dầu mỡ/S/P.'},
{q:'What is the appearance of lamellar tearing?', a:'Terraced / step-like appearance', vq:'Hình dạng xé lớp?', va:'BẬC THANG (terraced) trong kim loại nền.'},
{q:'Which is the best method to identify porosity?', a:'RT', vq:'(Ôn) Tìm rỗ khí?', va:'Chụp phim — đốm đen tròn.'},
{q:'How does porosity come (electrical cause)?', a:'High voltage (long arc)', vq:'(Ôn) Rỗ do điện?', va:'Áp cao/hồ quang dài.'},
{q:'In which material does distortion take place most?', a:'Austenitic stainless steel', vq:'Vật liệu nào biến dạng nhiều nhất?', va:'INOX AUSTENIT — giãn nở lớn, dẫn nhiệt kém.'},
{q:'Which two tests are required for welder qualification (fillet)?', a:'Fracture and macro', vq:'(Ôn) WQT mối góc?', va:'Bẻ gãy + macro.'},
{q:'In ferrous material defect testing, which NDT is applied?', a:'MPI (surface/near-surface)', vq:'Thép từ tính dùng NDT nào?', va:'MPI — nhạy, nhanh, rẻ trên thép.'},
{q:'Which MMA electrode gives a convex profile? Its name?', a:'7018 — basic', vq:'Que cho mối lồi?', va:'Bazơ 7018 (xỉ loãng, bead lồi).'},
{q:'In which transfer does lack of fusion occur? Reason?', a:'Dip transfer — low current (or too high inductance)', vq:'(Ôn) LOF ở transfer nào?', va:'Dip — năng lượng thấp.'},
{q:'Which electrode is good in PG position for root run welding? Which crack risk with it?', a:'E7010 cellulosic; hydrogen cracking risk', vq:'Que root PG & rủi ro?', va:'Cellulosic nhiều hydro → nguy cơ nứt nguội trên thép bền cao.'},
{q:'About the neutral flame?', a:'~50% O2 + 50% fuel gas — used to cut carbon steel & some low alloy steels', vq:'Ngọn lửa trung tính?', va:'O₂ ≈ gas — cắt thép C.'},
{q:'About the oxidising flame?', a:'More O2, less fuel — used for brass & bronze', vq:'Ngọn lửa oxy hóa?', va:'Thừa O₂ — đồng thau/đồng thanh.'},
{q:'About the carburising flame?', a:'Less O2, more fuel gas — used for lead & hard-facing', vq:'Ngọn lửa carbua hóa?', va:'Thừa gas — chì, tôi bề mặt.'},
{q:'Oxy-fuel gas cutting quality factors?', a:'Good cut vs: too slow, too fast, preheat flame too low/high, nozzle too high, irregular travel speed', vq:'Yếu tố chất lượng cắt oxy?', va:'Tốc độ, ngọn lửa nung, chiều cao bép, độ đều tay — sai 1 thứ là vệt cắt xấu.'},
{q:'About mechanised oxy-fuel cutting?', a:'Portable carriages or gantry machines — high productivity', vq:'Cắt oxy cơ giới?', va:'Xe rùa/máy giàn — năng suất cao, vệt đẹp.'},
{q:'About plasma cutting?', a:'No oxidation reaction needed, no preheat; gases: air, Ar, N2, O2, Ar+H2, N2+H2; cuts ALL materials (mainly stainless)', vq:'Cắt plasma?', va:'Cắt bằng NHIỆT hồ quang plasma — mọi vật liệu, chuyên inox/nhôm.'},
{q:'Manual metal arc gouging applied on which materials? Polarity?', a:'All materials; DCEN & AC', vq:'Đục MMA (gouging)?', va:'Que đục chuyên dụng — mọi vật liệu.'},
{q:'DRAG&DROP: Duties of a welding inspector DURING welding?', a:'Inter-pass cleaning, joint alignment (monitor), inter-pass temperature, gas flow rate', vq:'Nhiệm vụ TRONG khi hàn (kéo-thả)?', va:'Vệ sinh giữa lớp, thẳng hàng, nhiệt interpass, lưu lượng khí.'},
{q:'DRAG&DROP: Reasons for undercut?', a:'High current, high voltage, excessive weaving (+ high travel speed)', vq:'Nguyên nhân undercut (kéo-thả)?', va:'Dòng cao + áp cao + lắc rộng + đi nhanh.'},
{q:'Solidification cracking occurs due to…?', a:'Low melting point liquid films (high dilution, high restraint)', vq:'Nứt đông đặc do...?', va:'Màng lỏng điểm chảy thấp (FeS) + pha loãng cao + kìm hãm lớn.'},
{q:'Minimum intensity of light during visual inspection?', a:'350 Lux (recommended 500)', vq:'Ánh sáng tối thiểu khi VT?', va:'BS EN 13018: tối thiểu 350 lux, khuyến nghị 500 lux.'},
{q:'Solidification cracking is most likely in which process (121/131/135/141/136)?', a:'121 (SAW)', vq:'(Ôn) Quá trình dễ nứt nóng?', va:'SAW — bể sâu hẹp, pha loãng cao.'},
{q:'In all-weld test, which is NOT considered: Rm, Rp, Re, A%? Reason?', a:'Rp — yield point is difficult to determine for certain materials (Al, SS) — but C-Mn HAS defined yield so Rp not needed', vq:'(Ôn) Không đo Rp — lý do?', va:'Thép C-Mn có điểm chảy rõ → dùng Re; Rp chỉ cho vật liệu đường cong trơn.'},
{q:'In MMA process, if there was no root face, what will occur?', a:'Excess penetration (burn-through)', vq:'(Ôn) Không root face?', va:'Ngấu quá mức/cháy thủng.'},
{q:'The worst criteria for undercut?', a:'Sharpness + depth + length; sharpness → stress concentration', vq:'(Ôn) Undercut xấu nhất?', va:'SẮC là tệ nhất → tập trung ứng suất.'},
{q:'If changing from MMA to FCAW, what will happen?', a:'Deposition increases, distortion decreases', vq:'(Ôn) MMA→FCAW?', va:'Đắp nhanh hơn, ít biến dạng hơn.'},
{q:'Do you use AC current directly (from mains) for welding?', a:'No — transform it first, then use', vq:'Dùng điện lưới hàn thẳng?', va:'Phải qua BIẾN ÁP hạ áp trước.'},
{q:'WPS set in exam: which WPS for pipe-to-plate?', a:'Fillet weld WPS', vq:'Ống với tấm dùng WPS nào?', va:'Mối GÓC (fillet) → WPS fillet. Đề có 1 compound, 2 butt, 1 fillet.'},
{q:'Welder qualification for fillet weld — which test (no face/root bend)?', a:'Fracture test for fillet weld', vq:'(Ôn) WQT fillet thử gì?', va:'FRACTURE — không uốn được mối góc.'},
{q:'Which WPS is suitable for good root profile & high deposition?', a:'TIG (root) & SAW (fill) WPS combination', vq:'Root đẹp + đắp cao?', va:'TIG lót + SAW/FCAW phủ.'},
{q:'In welder qualification, which positions are NOT qualified (from all 4 WQT)?', a:'PD & PG', vq:'(Ôn) Tư thế không được duyệt?', va:'PD (trần góc) & PG (hàn xuống) — trùng đề WP1 câu 22.'},
{q:'Material thickness 12mm — which WQT can perform?', a:'Check each certificate thickness range (answer per exam: 2 valid)', vq:'12mm — chứng chỉ nào hợp lệ?', va:'Xét range 0,5t–2t của từng chứng chỉ → 2 chứng chỉ đạt (đề WP1 câu 9).'},
{q:'Which WPS has the lowest heat input?', a:'WPS with TIG', vq:'(Ôn) WPS HI thấp nhất?', va:'TIG (K=0,6).'},
{q:'Which factors are mentioned in a WPS?', a:'Preheat procedure, strong back, welding sequence (parameters, consumables, positions...)', vq:'WPS ghi những gì?', va:'Thông số hàn + preheat + trình tự + gá — mọi thứ thợ cần để hàn đúng.'},
{q:'Why is support provided during PWHT?', a:'To prevent collapse due to REDUCED yield strength at temperature; also for uniform heating', vq:'(Ôn) Chống đỡ khi PWHT?', va:'YS giảm khi nung → dễ sụp; kê đỡ + nung đều.', n:'Đề gốc có các phương án gây nhiễu (increase YS/UTS) — bản chất là YS GIẢM.'},
{q:'Which defects are detected by MPI?', a:'Surface & slightly subsurface cracks (NOT internal porosity/slag)', vq:'MPI phát hiện gì?', va:'Nứt bề mặt/sát bề mặt trên vật liệu từ tính.'},
{q:'E7018 — what is the 70?', a:'Minimum UTS 70,000 psi', vq:'(Ôn) 70 trong E7018?', va:'UTS tối thiểu 70 ksi.'},
{q:'Reasons for porosity (electrical)?', a:'High voltage, long arc length', vq:'(Ôn) Rỗ khí do điện?', va:'Áp cao = hồ quang dài = hút khí.'},
{q:'In TIG, a sharp tip is used in which polarity?', a:'DCEN (DC-)', vq:'(Ôn) Đầu nhọn TIG?', va:'DC- cho thép/inox; AC đầu tròn cho nhôm.'}
]};
