/* ============================================================
   THI BANK 5 — 42 câu kinh nghiệm thi (Cấp 2.2 — CUONG ND, tiếng Việt)
   Nguồn: "Tài liệu cấp 2.2.pdf"
   ============================================================ */
window.THI_C22 = {id:'c22', icon:'📝', vi:'42 câu kinh nghiệm thi (Cấp 2.2)', en:'42 exam experience notes', type:'card', items:[
{q:'Trong MMA nếu DC+ chuyển sang DC- thì xảy ra hiện tượng gì? Hướng đi electron/ion?', a:'Ngấu giảm, đắp tăng nhẹ. Electron: catot → anot; ion: anot → catot', va:'DC-: 2/3 nhiệt dồn về que → que chảy nhanh (đắp tăng) nhưng vật hàn nhận ít nhiệt (ngấu giảm).'},
{q:'Workpack: Tấm dày 40mm, root face = 5mm, root gap = 0mm thì hàn được process nào? (MMA, TIG, FCAW, SAW)', a:'SAW', va:'Root face dày + không khe hở → cần quá trình NGẤU SÂU: SAW (dòng rất lớn, hàn 2 phía). TIG/MMA không xuyên nổi 5mm không khe hở.'},
{q:'Undercut xảy ra ở tư thế hàn nào nhiều nhất (PA, PF, PG, PC)? Nguyên nhân?', a:'PC — do trọng lực kéo kim loại xệ xuống mép dưới, cạnh trên bị khuyết; dòng cao/tốc độ nhanh', va:'Hàn ngang PC: mép TRÊN dễ bị cháy chân vì kim loại lỏng chảy xuống. Kèm dòng cao + travel nhanh + WFS nhanh.'},
{q:'Gas flow hàn TIG là bao nhiêu? Tăng lưu lượng khí backing quá lớn thì lỗi gì?', a:'8–12 L/min; backing quá mạnh → root concavity (chân lõm)', va:'Khí lưng đẩy ngược bể hàn → chân lõm (suck-back).'},
{q:'Air arc gouging dùng dòng nào? Electron/ion đi thế nào?', a:'DCEP; electron đi từ vật hàn → điện cực carbon', va:'Thổi hồ quang carbon dùng ĐIỆN CỰC DƯƠNG (DCEP), khí nén thổi kim loại lỏng.'},
{q:'Lamellar tearing KHÔNG xảy ra ở mối hàn nào? Vì sao?', a:'Mối giáp mép (butt) — vì ứng suất dọc theo thớ cán, độ dẻo dọc cao', va:'Xé lớp cần lực kéo VUÔNG GÓC chiều dày (mối T, góc, nhánh). Butt joint kéo dọc tấm → không xé lớp.'},
{q:'2 số đầu của electrode trong ISO 2560 là gì, và AWS A5.18 là gì?', a:'ISO 2560: giới hạn chảy (E35=350MPa). AWS: độ bền kéo UTS (70=70ksi)', va:'ISO = YIELD; AWS = UTS. Câu bẫy kinh điển!'},
{q:'Ký hiệu nằm TRÊN đường reference/identification là của mặt nào?', a:'Other side (phía đối diện mũi tên) — theo ISO 2553', va:'ISO/EN: ký hiệu trên nét LIỀN = arrow side; trên nét ĐỨT (hoặc phía trên) = other side. AWS: dưới đường = arrow side, trên = other side.'},
{q:'Workpack: Argon vì sao gọi là khí TRƠ?', a:'Vì không phản ứng với môi trường/kim loại', va:'Khí trơ (inert) = không tham gia phản ứng hóa học với bể hàn (Ar, He). CO₂/O₂ là khí hoạt tính.'},
{q:'Workpack: ISO 14175: M12 HeArC được gọi là gì?', a:'Hỗn hợp He & Ar (+CO2 0,5–5%)', va:'M12-HeArC: nền Heli, cộng Argon và CO₂ thấp — khí hỗn hợp ít oxy hóa.'},
{q:'Toe blend sẽ giảm cái gì và góc bao nhiêu là hợp lý?', a:'Giảm tập trung ứng suất (tăng tuổi thọ mỏi); góc chân mối thoải 20–30°', va:'Chân mối (toe) chuyển tiếp mượt → giảm stress concentration → tăng fatigue life.'},
{q:'Workpack: Lengthening arc sẽ xảy ra gì?', a:'Volt tăng, ampe giảm', va:'Nguồn CC: hồ quang dài → điện áp tăng, dòng giảm → ngấu kém, rỗ khí, bắn tóe.'},
{q:'Vì sao góc bevel của inox (S.S) luôn nhỏ nhất? 2 hệ số của S.S?', a:'Chống biến dạng (giãn nở nhiệt lớn, dẫn nhiệt kém)', va:'Inox: hệ số GIÃN NỞ cao (~1,5× thép C) + DẪN NHIỆT thấp (~1/3) → thu hẹp góc vát để ít kim loại đắp, ít co ngót.'},
{q:'Workpack: "Stated as uphill" là position nào? (PA, PF, PC, PE)', a:'PF', va:'Uphill = hàn leo = PF. (Downhill = PG.)'},
{q:'Workpack: 309L & 316L — chữ L là gì?', a:'Low Carbon', va:'C ≤0,03% → giảm carbide crôm → chống weld decay.'},
{q:'Workpack: Trong BS EN 2560 thì RR ký hiệu gì?', a:'Rutile bọc dày (heavy rutile — thường kèm bột sắt)', va:'RR = vỏ rutin dày, đắp cao. (R = rutile thường.)'},
{q:'Workpack: S.S (inox) dùng các phương pháp NDT nào tối ưu?', a:'PT & RT', va:'Không dùng MT (không nhiễm từ); UT bị nhiễu hạt thô → PT (bề mặt) + RT (bên trong).'},
{q:'2 nguyên tố nào ngăn ngừa weld decay? Vì sao?', a:'Ti / Nb — vì chúng kết hợp với carbon trước Cr', va:'Ti, Nb tạo carbide bền với C → C không lấy Cr → biên hạt không nghèo Cr (mác 321=Ti, 347=Nb).'},
{q:'Trước khi hàn, nhiệm vụ chính của inspector là gì?', a:'Kiểm tra hồ sơ (WPS, chứng chỉ thợ, vật liệu, ITP), gá lắp, vát mép, làm sạch, preheat... (Chương 1)', va:'TRƯỚC hàn: document check + material check + fit-up + preparation + preheat. Học kỹ Chương 1!'},
{q:'Ống S.S hàn với plate C.S thì cái nào biến dạng nhiều nhất? Tấm hay ống?', a:'Tấm (plate)', va:'Ống có độ cứng hình học (dạng tròn) → tấm phẳng biến dạng nhiều hơn.'},
{q:'Ứng suất dư dẫn đến cái gì? Bề mặt gãy của nó?', a:'Gãy giòn (brittle) — bề mặt tinh thể sáng (crystalline)', va:'Ứng suất dư + nhiệt độ thấp/khuyết tật → gãy giòn; mặt gãy phẳng, sáng lấp lánh, có vân chevron.'},
{q:'Ứng suất dư xảy ra ở điểm nào của yield? Gây biến dạng gì?', a:'Dưới yield point; biến dạng đàn hồi (elastic deformation)', va:'Ứng suất dư tồn tại DƯỚI giới hạn chảy (nếu vượt thì đã biến dạng dẻo xả bớt); gây biến dạng đàn hồi trong kết cấu.'},
{q:'Yếu tố nào gây ra HICC (ductile, heat input, toughness, Y.S)? ', a:'Heat input (câu sau liên quan tới hardness)', va:'Trong 4 lựa chọn: HEAT INPUT quyết định tốc độ nguội → độ cứng → HICC. Câu tiếp theo hỏi về độ cứng >400HV.'},
{q:'Hàn trần (overhead) thì dùng khí nào (mostly)? — Ar, He, CO2, O2', a:'Helium', va:'He NHẸ HƠN không khí → bay LÊN, che phủ tốt khi hàn trần. Ar nặng → rơi xuống, hợp hàn sấp.'},
{q:'Khí nào nguy hiểm trong không gian kín? Vì sao?', a:'Argon (đề có thể cho cả CO2/H2S) — displace air, chiếm chỗ oxy gây ngạt', va:'Ar không màu không mùi, nặng, tích ở đáy → ngạt không có dấu hiệu báo trước. Đề hay chọn Ar.'},
{q:'Bộ chuyển đổi trong MMA transformer-rectifier là gì?', a:'AC → DC (chỉnh lưu)', va:'Transformer hạ áp tăng dòng (AC-AC); RECTIFIER chỉnh lưu AC→DC.'},
{q:'Workpack: Tính HI và Arc energy?', a:'AE=(V×A×60)/(speed×1000); HI=K×AE', va:'Nhớ nhân 60 (đổi phút→giây) và K: TIG 0,6; MMA/MAG/FCAW 0,8; SAW 1,0.'},
{q:'Quenching & tempering thì thép sẽ như thế nào? Dùng destructive testing nào kiểm tra?', a:'Tôi: cứng & bền tăng, dẻo dai giảm; ram: phục hồi độ dai. Kiểm bằng thử độ cứng (+ va đập)', va:'Tôi tạo martensite cứng; ram 550–600°C giảm giòn. Thử hardness & impact để so cơ tính.'},
{q:'Muốn chuyển từ spray sang dip thì khí CO2 tăng hay giảm? Vì sao?', a:'CO2 tăng (VD từ Ar+5%CO2 sang Ar+20%CO2 hoặc 100% CO2)', va:'CO₂ nhiều → hồ quang "cứng", không duy trì được spray → chuyển dip/globular. 100% CO₂ chỉ hàn dip.'},
{q:'Dip là voltage bao nhiêu? Nếu tăng volt mà ampe không đổi thì chuyển dịch nào?', a:'<24V; tăng volt → globular', va:'Dip <24V. Tăng áp giữ dòng → giọt to lủng lẳng = GLOBULAR (bắn tóe nhiều).'},
{q:'Workpack: Tính throat — nhân với 0.7 hay 0.707?', a:'a = z × 0.707 (thi lấy 0.7 nếu đáp án tròn)', va:'Chuẩn: cos45°=0,707. Đề cho đáp án 8,4 với z=12 → dùng 0,7.'},
{q:'Hot shortness là gì?', a:'Nứt/giòn ở nhiệt độ cao do pha điểm chảy thấp (FeS) — liên quan low melting point', va:'"Giòn nóng": màng FeS chảy ở ~988°C giữa biên hạt → nứt khi co ngót. Chính là cơ chế nứt đông đặc.'},
{q:'Mối hàn chữ gì gây ra ít biến dạng nhất?', a:'Chữ U (ít kim loại đắp)', va:'U/J cần ít kim loại đắp nhất → ít co ngót nhất (nhưng gia công đắt).'},
{q:'Welding process nào phù hợp hàn site với yêu cầu PF + high deposition rate?', a:'FCAW (136)', va:'Dây lõi thuốc: đắp cao, hàn leo tốt, cơ động ngoài công trường.'},
{q:'Workpack: Khi nào/tại sao MT hiệu quả hơn PT khi tìm khuyết tật hở bề mặt?', a:'MT nhanh hơn, thấy cả khuyết tật sát bề mặt, chỉ thị không loang; PT chỉ khuyết tật hở, chậm (10-30 phút), loang bleed-out', va:'MT: nhanh, phát hiện nứt bề mặt + gần bề mặt, làm được qua lớp sơn mỏng. PT: mọi vật liệu nhưng chỉ khuyết tật HỞ, tốn thời gian thấm.'},
{q:'Autogenous joint là gì?', a:'Mối hàn TIG không dùng que phụ (no filler)', va:'Tự nóng chảy 2 mép — chỉ tấm mỏng; dễ lõm chân/thiếu ngấu.'},
{q:'111, 141, 135, 136: cái nào hydrogen nhỏ nhất, cái nào lớn nhất?', a:'141 (TIG) min; 111 (MMA) max — nhất là que cellulosic', va:'TIG sạch nhất (H2 thấp nhất). MMA cao nhất do vỏ thuốc (cellulosic chứa nhiều H2 nhất).'},
{q:'Workpack: Vật liệu thép trắng (inox) — NDT nào phù hợp tìm khuyết tật bề mặt VÀ bên trong?', a:'PT + RT', va:'Bề mặt PT (không từ), bên trong RT (UT nhiễu hạt thô).'},
{q:'Root face khác nhau (2 bên không đều) thì có rủi ro gì?', a:'Thiếu ngấu chân phía dày / ngấu quá phía mỏng', va:'Chức năng root face: chống cháy thủng + đảm bảo ngấu. Không đều = ngấu không đều.'},
{q:'Workpack: Fillet weld — throat lớn hơn leg length thì là hình dạng gì?', a:'Mối hàn LỒI (convex) — a > 0.7z chứng tỏ đắp dư', va:'Vẽ tam giác: nếu a đo được > 0,707×z → bề mặt lồi. Lõm (concave) thì a < 0,707z.'},
{q:'Workpack: Slow travel speed thì bị gì?', a:'HI tăng, mối rộng, ngấu sâu/tràn (cold lap), hạt thô giảm dai', va:'Đi chậm: bể hàn to, kim loại chảy đè lên trước → cold lap/overlap; HI cao mất toughness.'},
{q:'Hàn stainless steel tại sao dùng góc bevel NHỎ hơn?', a:'Giảm kim loại đắp → giảm biến dạng (giãn nở nhiệt cao, dẫn nhiệt kém)', va:'Càng ít kim loại đắp càng ít co ngót — quan trọng gấp đôi với inox vì nó biến dạng mạnh.'}
]};
