/* ============================================================
   THI BANK 3 — WPS Technology Ring 1 & 2, Điền khuyết, Kéo-thả, Câu hỏi thêm
   Nguồn: "TÀI LIỆU CẤP 1 - Phần 1.pdf"
   (†) = đáp án do trợ lý bổ sung vì tài liệu gốc thiếu key — đã kèm giải thích
   ============================================================ */
window.THI_RING = {id:'ring', icon:'⚙️', vi:'WPS Technology Ring 1+2 (40 câu)', en:'WPS Technology Rings', type:'mcq', items:[
{q:'R1-1. Prior to manufacturing, the engineer has requested a change in welding process from MMA to FCAW. What would be the result of this?', o:['Increased deposition rate and reduction in distortion','Increase in residual stresses and tungsten inclusion','Increased risk of HICC and a reduction in deposition rate','Increased risk of lamellar tearing and reduction in deposition rate'], a:0, vq:'Đổi từ MMA sang FCAW — kết quả?', va:'FCAW (dây lõi thuốc) ĐẮP NHANH hơn, ít lần dừng → ít biến dạng hơn.'},
{q:'R1-2. Why is the use of a sharp hard stamp no longer recommended?', o:['They can reduce the toughness of a material','They are stress raisers','They accelerate the effect of cold working on a material','Their use is still recommended for all identifications on metal'], a:1, vq:'Vì sao không nên dùng dấu đóng SẮC (hard stamp)?', va:'Vết đóng sắc = ĐIỂM TẬP TRUNG ỨNG SUẤT (stress raiser) → khởi phát nứt mỏi. Dùng dấu đáy tròn (low-stress stamp).'},
{q:'R1-3. You discover prior to welding that the material grade specified is not the one being used. What will be the course of action?', o:['Allow the operation to commence as long as you make a note of the change','Request a new procedure be tested for the new grade','Carry out a bend test to check the properties before allowing their use','Request confirmation from the engineer that the new grade is suitable'], a:1, vq:'Vật liệu không đúng mác — làm gì?', va:'Key Ring 1: B — yêu cầu QUALIFY QUY TRÌNH MỚI cho mác mới. (Đề Work Pack 1 câu tương tự chọn D — hỏi ý kiến kỹ sư. Đọc kỹ ngữ cảnh!)', n:'2 bộ đề 2 đáp án (B vs D) — tùy ngữ cảnh câu hỏi.'},
{q:'R1-4. A single bevel has been prepared when the drawing specifies a single V. What could occur with this change?', o:['Easier to weld','Possibility of lack of sidewall fusion','An increase in deposition rate','A decrease in deposition rate'], a:3, vq:'Chuẩn bị single bevel thay vì single V?', va:'Key Ring 1: D (giảm tốc độ đắp). Work Pack 1 câu tương tự chọn B (nguy cơ LOF mặt đứng). Ghi nhớ cả 2 hướng đáp án.', n:'Key gốc Ring 1 = D; WP1 = B. Bản chất kỹ thuật thiên về LOF ở mặt đứng.'},
{q:'R1-5. You notice that prior to welding a V butt does not have any root faces which had been stipulated. What issue could this cause?', o:['A decrease in root penetration','An increase in root penetration','Decrease in root fusion','No problems would occur'], a:1, vq:'Mối V không có root face — hậu quả?', va:'Không có mặt đáy hãm nhiệt → NGẤU QUÁ / cháy thủng (excess penetration).'},
{q:'R1-6. During welding you see a change from stringer to weaving. What would be the consequence of this?', o:['Increase in hardness in the HAZ','Decrease in toughness in the HAZ','Decrease in heat input','Poor weld profile'], a:1, vq:'Đổi từ đường thẳng (stringer) sang lắc que (weaving) — hậu quả?', va:'Weaving đi chậm → HEAT INPUT TĂNG → hạt thô → GIẢM ĐỘ DAI vùng HAZ.'},
{q:'R1-7. When do you measure the interpass temperature?', o:['1 minute prior to the next run','Only after the root run','Prior to commencing the next run','Only at the start of the welding operation'], a:2, vq:'Đo interpass khi nào?', va:'Ngay TRƯỚC khi hàn đường tiếp theo — câu này lặp lại ở mọi đề!'},
{q:'R1-8. The welder accidentally initiates the arc outside of the joint in HSLA steel. What would be your course of action as the defect is unacceptable to the given criteria?', o:['Nothing at all','Clean it with a sander','Grind it and inspect with MPI','If the material is not too soft it should be fine'], a:2, vq:'Arc strike ngoài mối hàn trên thép HSLA — xử lý?', va:'MÀI SẠCH + MPI kiểm tra nứt. Arc strike trên HSLA tạo vùng tôi cứng cục bộ rất dễ nứt.'},
{q:'R1-9. During MMA welding, you notice the welder is varying arc length during welding. What would the consequences be?', o:['When the arc is shortened the current will increase','Shortening the arc will decrease penetration','Lengthening the arc will increase the current','Travel speed will be influenced'], a:0, vq:'Thợ thay đổi chiều dài hồ quang khi hàn MMA — hệ quả?', va:'Hồ quang NGẮN → áp giảm, DÒNG TĂNG (nguồn CC) → ngấu sâu hơn. Dài → ngược lại + rỗ khí.'},
{q:'R1-10. While measuring the run out length you notice that the welder has increased the run out length on one of the filling runs. What will be the effect of this?', o:['Increased hardness','Increased distortion','Decreased hardness','Increased toughness'], a:0, vq:'Tăng run-out length lớp đắp — hậu quả?', va:'ROL tăng = HI giảm = nguội nhanh → TĂNG ĐỘ CỨNG (nguy cơ HICC).'},
{q:'R1-11. During welding you notice that the welder is above the maximum heat input as stated on the WPS, several runs before the completion of the joint. What action would you take?', o:['Reject the weld','Advise the welder to decrease travel speed','Let the welder complete the joint','Advise the welder to change polarity'], a:0, vq:'Vượt HI max giữa chừng — hành động?', va:'REJECT — mối hàn không tuân thủ WPS. (Giảm travel speed còn làm HI tăng thêm!)'},
{q:'R1-12. During visual inspection you observe excessive spatter on the surface; the welding process used was MAG. What could be the cause?', o:['Excessive inductance','Too low a gas flow rate','Low inductance','Excessive gas flow rate'], a:2, vq:'Bắn tóe nhiều khi hàn MAG — nguyên nhân?', va:'INDUCTANCE THẤP → dòng đoản mạch tăng vọt → nổ giọt → bắn tóe.'},
{q:'R1-13. When the weld has been completed on a high integrity 316L material joint, you notice some strong-backs have been removed, ripping out some parent metal. What will be your course of action?', o:['Perform grinding and MPI','Nothing, accept it','Implement repair procedure','Let the welder repair it'], a:2, vq:'Tháo strong-back làm RÁCH kim loại nền 316L — xử lý?', va:'Phải SỬA THEO QUY TRÌNH SỬA CHỮA ĐÃ DUYỆT (repair procedure). Không MPI được vì 316L không nhiễm từ!'},
{q:'R1-14. A joint requires NDT testing. What would be the best method for finding internal planar defects?', o:['UT','RT','MT','PT'], a:0, vq:'Tìm khuyết tật PHẲNG bên trong — dùng gì?', va:'UT (siêu âm) — sóng âm phản xạ mạnh từ khuyết tật phẳng (LOF, nứt). RT dễ bỏ sót khuyết tật phẳng.'},
{q:'R1-15. On the ITP it is stated that NDT will be carried out 48 hours after welding. What is the reason for this?', o:['Hot cracking','Lamellar tearing','Cold cracking','Ductile failure'], a:2, vq:'Chờ 48h mới NDT — lý do?', va:'NỨT NGUỘI (cold cracking/HICC) xuất hiện trễ 48–72h sau hàn.'},
{q:'R1-16. Why is it important to put supports onto the structure during PWHT?', o:['During PWHT some material may begin to collapse','During PWHT the material\'s yield point increases','It prevents collapse in a structure due to increased UTS','It allows the structure to heat up evenly'], a:0, vq:'Vì sao phải kê đỡ khi PWHT?', va:'Ở nhiệt độ PWHT (550–600°C) giới hạn chảy GIẢM mạnh → kết cấu có thể TỰ SỤP nếu không kê đỡ. (Đề WP1 chọn phương án C — nhớ cả 2!).', n:'Ring 1 key = A; WP1 key = C cho câu tương tự.'},
{q:'R1-17. The pipe work needs to be hydrostatically tested. What preparation is necessary to perform this test?', o:['Check pressure gauges are calibrated','Check pipe work is air tight','Ensure sufficient air pressure is available','Heat the water before testing'], a:0, vq:'Chuẩn bị gì trước thử thủy tĩnh?', va:'(†) Kiểm tra ĐỒNG HỒ ÁP đã hiệu chuẩn — giống đề WP1 câu 30 (key A).', n:'† Tài liệu gốc thiếu key câu 17-20; đáp án bổ sung theo đề WP1 & lý thuyết.'},
{q:'R1-18. In the welding documentation, you notice that the NDT report is missing. What would be your course of action?', o:['Ignore this','Copy another NDT report and change the joint number','Write the NDT report','Retest the weld and place the report in the welding documents'], a:3, vq:'Thiếu báo cáo NDT trong hồ sơ — làm gì?', va:'(†) KIỂM TRA LẠI mối hàn và bổ sung báo cáo — như đề WP1 câu 31 (key D). Tuyệt đối không giả mạo hồ sơ.', n:'†'},
{q:'R1-19. The client has requested a part to be replaced with 316L. What would be the issue when welding this joint (S355 to 316L)?', o:['Solidification cracking due to high sulphur content of S355','There is a high risk of weld decay due to the high carbon level in C-Mn steel','Low risk of weld decay due to the low carbon level of 316L','Increased risk of lamellar tearing due to poor through-thickness ductility of 316L'], a:1, vq:'Hàn S355 với 316L — vấn đề gì?', va:'(†) Cacbon từ thép C-Mn khuếch tán/pha loãng vào mối inox → nguy cơ WELD DECAY (nhạy cảm hóa). Tài liệu 2.1 ghi "ae tự ngâm cứu" — các lớp học chọn đáp án này.', n:'† Câu tranh luận; một số nơi chọn solidification cracking. Nhớ ngữ cảnh "weld decay vì có C".'},
{q:'R1-20. If the material was changed to 316L, what NDT method could not be used?', o:['DT','RT','MT','Phased array testing'], a:2, vq:'Vật liệu 316L — NDT nào KHÔNG dùng được?', va:'(†) MT (bột từ) — 316L austenit KHÔNG NHIỄM TỪ. Trùng key đề WP1 câu 23.', n:'†'},
{q:'R2-1. For a 5mm root face with no gap, what is the effect of this?', o:['To prevent distortion','Increase in deposition','Allow full penetration during TIG','To allow SAW'], a:0, vq:'Root face 5mm, không khe hở — mục đích?', va:'(†) CHỐNG BIẾN DẠNG (ít kim loại đắp, co ngót cân bằng) — trùng key đề WP2 câu 29.', n:'† Ring 2 gốc không có key; đáp án theo WP2.'},
{q:'R2-2. Highest preheat is required for which weld preparation?', o:['Single V','Compound','Asymmetrical','Double V'], a:1, vq:'Kiểu mối nào cần preheat CAO nhất?', va:'(†) COMPOUND (mối tổ hợp) — nhiều đường thoát nhiệt → nguội nhanh nhất. Trùng key WP2 câu 34.', n:'†'},
{q:'R2-3. Which electrode is best to use in J-L045?', o:['7016','6010','6013','7018'], a:1, vq:'Que nào hợp J-L045 (hàn xuống)?', va:'(†) E6010 cellulosic — chuyên hàn ống tiến XUỐNG. Trùng key WP2 câu 32.', n:'†'},
{q:'R2-4. What is the effect when we go from argon to helium in MIG?', o:['Increased HAZ','Decreased HAZ','Decreased arc volume','None of the above'], a:0, vq:'Đổi argon → heli trong MIG?', va:'(†) Heli cho hồ quang NÓNG hơn → HAZ RỘNG hơn, ngấu sâu hơn. (WP2 câu 13: "increase heating affect".)', n:'†'},
{q:'R2-5. What is the effect on the weld profile when the backing gas flow rate is higher than the shielding gas flow rate?', o:['Lack of sidewall fusion','Root concavity','Burn through','Spatter'], a:1, vq:'Khí lưng mạnh hơn khí bảo vệ?', va:'(†) CHÂN LÕM (root concavity) — áp lực đẩy ngược bể hàn. Trùng key WP2 câu 35.', n:'†'},
{q:'R2-6. (Gas M12) What are the first and second digit gases?', o:['Argon and Helium','Helium and CO2','Helium and Argon','Hydrogen and Argon'], a:2, vq:'Khí M12: 2 thành phần ký hiệu đầu?', va:'(†) Helium và Argon (M12–HeArC: He nền + Ar + 0,5–5% CO₂). Trùng key WP2 câu 26.', n:'†'},
{q:'R2-7. If the root face is 4mm and root gap is 2mm, what is the effect of this?', o:['Excessive penetration','Poor profile','Lack of root penetration','No issue'], a:2, vq:'Root face 4mm, khe hở chỉ 2mm?', va:'(†) Mặt đáy dày + khe hẹp → THIẾU NGẤU CHÂN (LOP).', n:'†'},
{q:'R2-8. In which welding process is higher deposition achieved in PF?', o:['121','136','111','135'], a:1, vq:'Quá trình nào đắp cao nhất ở tư thế PF?', va:'(†) 136 (FCAW) — dây lõi thuốc đắp cao và hàn leo tốt. Trùng key WP2 câu 21.', n:'†'},
{q:'R2-9. If the welder is lengthening the arc, what will be the effect of this?', o:['Increase in current','Decrease in current','Travel speed decreases current','Increase in toughness'], a:1, vq:'Kéo dài hồ quang → dòng?', va:'(†) DÒNG GIẢM (nguồn CC: áp tăng thì dòng giảm). Trùng key WP2 câu 5.', n:'†'},
{q:'R2-10. In which welding processes is constant voltage used?', o:['SAW and MAG','SAW and MMA','MMA and TIG','MMA'], a:0, vq:'Quá trình nào dùng nguồn CV (áp không đổi)?', va:'(†) SAW & MIG/MAG — dây cấp liên tục cần tự điều chỉnh chiều dài hồ quang (self-adjusting arc). MMA/TIG dùng CC.', n:'†'},
{q:'R2-11. What is the effect when preheat is decreased?', o:['Heat input increases','Heat input decreases','Hardness increases','Toughness increases'], a:2, vq:'Giảm preheat → hệ quả?', va:'(†) Nguội nhanh hơn → ĐỘ CỨNG TĂNG → nguy cơ HICC.', n:'†'},
{q:'R2-12. What will be the design throat thickness of a fillet weld with a leg length of 0.7mm?', o:['0.78mm','0.89mm','0.63mm','0.49mm'], a:3, vq:'Leg 0,7mm → throat thiết kế?', va:'(†) a = z×0,7 = 0,7×0,7 = 0,49mm.', n:'†'},
{q:'R2-13. Which of the following is NOT an essential variable in a WPS for the SMAW process?', o:['Electrode classification','Current type and polarity','Welding position','Welder\'s certification'], a:3, vq:'Cái nào KHÔNG phải biến số thiết yếu của WPS (SMAW)?', va:'(†) Chứng chỉ THỢ HÀN thuộc về welder qualification, không phải biến số của WPS.', n:'†'},
{q:'R2-14. In a WPS for the GTAW process, what parameter ensures adequate shielding of the weld pool?', o:['Welding current','Shielding gas flow rate','Preheat temperature','Root gap'], a:1, vq:'Thông số nào bảo đảm che chắn bể hàn TIG?', va:'(†) LƯU LƯỢNG KHÍ BẢO VỆ (thường 8–12 L/phút).', n:'†'},
{q:'R2-15. According to ASME Section IX, a change in which of the following parameters requires requalification of the WPS?', o:['Welding voltage','Filler metal classification','Type of backing material','Weld bead shape'], a:1, vq:'Theo ASME IX, đổi gì phải qualify lại WPS?', va:'(†) Đổi PHÂN LOẠI VẬT LIỆU HÀN (F-number/A-number) = biến số thiết yếu → requalify.', n:'†'},
{q:'R2-16. For a WPS, the specified heat input is calculated using which formula?', o:['(Voltage × Current) / Travel Speed','(Voltage × Current) / Arc Length','(Current × Time) / Weld Area','(Voltage × Current × Weld Speed)'], a:0, vq:'Công thức heat input?', va:'(†) HI = (U×I)/tốc độ hàn (×60/1000 nếu ra kJ/mm, nhân thêm K theo quá trình).', n:'†'},
{q:'R2-17. Which parameter in a WPS directly affects the cooling rate of the weld?', o:['Preheat temperature','Filler metal diameter','Electrode coating type','Arc length'], a:0, vq:'Thông số nào ảnh hưởng trực tiếp tốc độ nguội?', va:'(†) NHIỆT ĐỘ GIA NHIỆT TRƯỚC (preheat) — preheat cao → nguội chậm → mềm hơn, ít HICC.', n:'†'},
{q:'R2-18. In ISO 15614, the range of approval for plate thickness during WPS qualification is determined by?', o:['The number of passes used','Base material thickness','Specified heat input range','Weld bead width'], a:1, vq:'Phạm vi duyệt chiều dày (ISO 15614) dựa vào gì?', va:'(†) CHIỀU DÀY MẪU THỬ (test piece thickness t) → phạm vi ví dụ 0,5t–2t.', n:'†'},
{q:'R2-19. What is the purpose of a Procedure Qualification Record (PQR) in relation to a WPS?', o:['To document welder performance qualification','To establish the mechanical properties of the weld','To outline the parameters of a welding procedure','To approve visual inspection criteria'], a:1, vq:'PQR/WPQR dùng để làm gì?', va:'(†) GHI NHẬN KẾT QUẢ THỬ (cơ tính đạt) chứng minh WPS cho mối hàn đạt yêu cầu.', n:'†'},
{q:'R2-20. What test is mandatory for WPS qualification of pressure vessel welds under ASME Section IX?', o:['Hardness test','Charpy impact test','Bend test','Radiographic test'], a:2, vq:'Thử nào BẮT BUỘC khi qualify WPS bình áp lực (ASME IX)?', va:'(†) THỬ UỐN (+ kéo) là bắt buộc trong QW-451. Impact/hardness chỉ khi có yêu cầu bổ sung.', n:'†'}
]};

window.THI_FB = {id:'fb', icon:'✏️', vi:'Điền khuyết & Ứng suất dư (23 câu)', en:'Fill in the blanks', type:'mcq', items:[
{q:'FB1. Which value would be an important factor with regards to residual stress?', o:['Hardness','Yield strength','UTS value','Charpy impact value'], a:1, vq:'Đại lượng nào quan trọng với ỨNG SUẤT DƯ?', va:'(†) Ứng suất dư tối đa xấp xỉ GIỚI HẠN CHẢY (yield) của vật liệu.', n:'† Bộ này tài liệu không in key; đáp án kèm giải thích chuẩn giáo trình.'},
{q:'FB2. To reduce residual stresses, which of the following would be most effective?', o:['Peening','Toe grinding','Post hydrogen release','PWHT'], a:3, vq:'Cách hiệu quả nhất để GIẢM ứng suất dư?', va:'(†) PWHT (nhiệt luyện sau hàn / stress relief) — nung 550–600°C cho ứng suất "chùng" ra.', n:'†'},
{q:'FB3. Residual stresses are consequences of?', o:['The material\'s yielding','The material\'s not yielding','The material\'s toughness','The material\'s hardness'], a:0, vq:'Ứng suất dư sinh ra do đâu?', va:'(†) Do co ngót bị KÌM HÃM làm vật liệu CHẢY DẺO cục bộ quanh mối hàn → khi nguội tồn tại ứng suất dư (dưới mức yield).', n:'†'},
{q:'FB4. Necking?', o:['Is when elastic point is reached','Is when proof stress is reached','Is when the specimen has gone past its elastic point and is moving into the plastic zone','Is the point just before failure'], a:2, vq:'"Necking" (thắt cổ mẫu kéo) là gì?', va:'(†) Xảy ra khi mẫu vượt qua vùng đàn hồi, vào vùng CHẢY DẺO (sau UTS thì thắt rõ) → tiết diện giảm cục bộ trước khi đứt.', n:'†'},
{q:'FB5. In WPS qualification, the ____ variable must be requalified if the welding process changes.', o:['Essential','Non-essential','Supplementary essential','Optional'], a:0, vq:'Đổi quá trình hàn → phải qualify lại biến số nào?', va:'(†) Biến số THIẾT YẾU (essential variable) — đổi là phải làm lại WPQR.', n:'†'},
{q:'FB6. The primary purpose of a ____ test is to measure the weld metal\'s toughness at low temperatures.', o:['Tensile','Bend','Impact','Hardness'], a:2, vq:'Thử gì đo ĐỘ DAI ở nhiệt độ thấp?', va:'(†) IMPACT (Charpy V) — đo năng lượng hấp thụ (J) ở nhiệt độ quy định.', n:'†'},
{q:'FB7. During GTAW, the ____ electrode is used for creating the arc but does not melt.', o:['Tungsten','Carbon','Copper','Steel'], a:0, vq:'Điện cực TIG làm bằng gì?', va:'(†) WOLFRAM (tungsten) — nóng chảy 3410°C, không nóng chảy khi hàn (non-consumable).', n:'†'},
{q:'FB8. The ____ test is used to determine internal weld defects such as porosity and slag inclusions.', o:['Radiographic','Visual','Liquid penetrant','Magnetic particle'], a:0, vq:'Thử gì tìm rỗ khí + xỉ bên trong?', va:'(†) RT (chụp phim) — khuyết tật thể tích hiện rõ trên phim.', n:'†'},
{q:'FB9. The ____ process uses a consumable electrode coated with flux to create the weld.', o:['SMAW','GTAW','GMAW','SAW'], a:0, vq:'Quá trình nào dùng que chảy bọc thuốc?', va:'(†) SMAW/MMA (111) — que hàn có vỏ thuốc bọc.', n:'†'},
{q:'FB10. Preheating is required for welding materials with high ____ to reduce the risk of cracking.', o:['Thermal conductivity','Carbon equivalent','Hardness','Tensile strength'], a:1, vq:'Preheat cần cho vật liệu có ____ cao?', va:'(†) CEV (carbon equivalent) cao → dễ tôi cứng → cần preheat chống nứt nguội. CEV>0,45 thường phải preheat.', n:'†'},
{q:'FB11. In visual inspection, the ____ angle should be adequate to identify surface defects.', o:['Reflection','Observation','Lighting','Distortion'], a:1, vq:'Góc ____ phải phù hợp khi kiểm tra ngoại quan?', va:'(†) Góc NHÌN (observation/viewing angle >30°, khoảng cách ≤600mm, ánh sáng ≥350 lux).', n:'†'},
{q:'FB12. For low-alloy steels, the ____ electrode is commonly used to maintain strength and ductility.', o:['E6010','E7018','ER70S-6','E308'], a:1, vq:'Thép hợp kim thấp dùng que gì?', va:'(†) E7018 — bazơ hydro thấp, cơ tính cao, giữ độ dẻo dai.', n:'†'},
{q:'FB13. In magnetic particle testing, ____ particles are used to identify surface and near-surface defects.', o:['Non-metallic','Ferromagnetic','Metallic','Diamagnetic'], a:1, vq:'MT dùng hạt gì?', va:'(†) Hạt SẮT TỪ (ferromagnetic) — bị hút vào chỗ rò rỉ từ thông.', n:'†'},
{q:'FB14. The ____ is used in welding to prevent atmospheric contamination of the molten pool.', o:['Flux','Shielding gas','Electrode','Weld bead'], a:1, vq:'Cái gì bảo vệ bể hàn khỏi không khí?', va:'(†) KHÍ BẢO VỆ (với MIG/TIG). Với MMA/SAW thì là thuốc/xỉ — đề hỏi chung → shielding gas.', n:'†'},
{q:'FB15. The ____ position is the most challenging for welders due to gravitational effects.', o:['Flat','Horizontal','Vertical','Overhead'], a:3, vq:'Tư thế khó nhất do trọng lực?', va:'(†) HÀN TRẦN (overhead/PE) — kim loại lỏng bị trọng lực kéo rơi.', n:'†'},
{q:'FB16. To ensure proper fusion between passes, ____ temperature must be controlled.', o:['Base metal','Preheat','Interpass','Cooling'], a:2, vq:'Nhiệt độ gì phải kiểm soát giữa các lớp?', va:'(†) INTERPASS — đo trước mỗi đường hàn kế tiếp.', n:'†'},
{q:'FB17. The ____ test involves bending a welded specimen to assess ductility and fusion.', o:['Bend','Tensile','Impact','Hardness'], a:0, vq:'Thử gì uốn mẫu đánh giá độ dẻo & độ ngấu?', va:'(†) BEND test — lộ khuyết tật LOF, độ dẻo mặt/chân mối.', n:'†'},
{q:'FB18. The ____ group numbers in ASME Section IX categorise metals based on similar weldability.', o:['F-Number','P-Number','A-Number','T-Number'], a:1, vq:'ASME IX nhóm KIM LOẠI CƠ BẢN theo số gì?', va:'(†) P-NUMBER (base metal). F-number = que/dây hàn; A-number = phân tích hóa học kim loại đắp.', n:'†'},
{q:'FB19. The ____ defect occurs when the weld bead fails to penetrate the joint completely.', o:['Porosity','Lack of fusion','Undercut','Lack of penetration'], a:3, vq:'Khuyết tật khi mối không xuyên hết chiều dày?', va:'(†) LACK OF PENETRATION (thiếu ngấu chân/LOP).', n:'†'}
]};

window.THI_DD = {id:'dd', icon:'🧩', vi:'Kéo–thả & Câu hỏi thêm từ đề thật (12 mục)', en:'Drag & drop + extra', type:'card', items:[
{q:'DRAG&DROP: Which of the following are the parts of a MIG/MAG torch?', a:'Nozzle, Spatter protection, Welding gun assembly, Gas diffuser, Contact tip, Spot welding spacer, Welding gun body, On/Off switch, Hose port', vq:'Các bộ phận của mỏ hàn MIG/MAG?', va:'Chụp khí (nozzle), chống bắn tóe, cụm súng hàn, bộ khuếch tán khí, BÉP TIẾP ĐIỆN (contact tip), thân súng, công tắc, cổng ống dẫn.'},
{q:'DRAG&DROP: Which of the following would you measure in tensile testing?', a:'ReL (lower yield), ReH (upper yield), Rm (UTS), Elongation A%', vq:'Thử kéo đo những gì?', va:'ReL/ReH (giới hạn chảy dưới/trên), Rm (độ bền kéo), A% (độ giãn dài). Thép C-Mn không cần Rp.'},
{q:'DRAG&DROP: What are the factors of HICC?', a:'Hardness > 400HV; Temperature < 300°C; Stress > 0.5 yield; Hydrogen > 15ml/100g weld metal', vq:'4 yếu tố gây nứt nguội hydro?', va:'CỨNG >400HV + NHIỆT <300°C + ỨNG SUẤT >0,5YS + HYDRO >15ml/100g. Thiếu 1 trong 4 thì không nứt.'},
{q:'DRAG&DROP: What are the factors affecting residual stresses?', a:'Parent material properties, Amount of restraint, Joint design, Fit-up, Welding sequence', vq:'Yếu tố ảnh hưởng ứng suất dư?', va:'Tính chất vật liệu nền, mức độ KÌM HÃM (restraint), thiết kế mối, gá lắp, thứ tự hàn.'},
{q:'EXTRA: The cost of repairing a weld is ____ times higher than the original weld.', a:'10 times', vq:'Chi phí sửa mối hàn gấp mấy lần hàn mới?', va:'Gấp 10 LẦN — vì phải NDT, đục bỏ, hàn lại, kiểm tra lại.'},
{q:'EXTRA: Iron sulphide is present in which cracking?', a:'Solidification cracking (nứt nóng)', vq:'Sunfua sắt (FeS) liên quan nứt gì?', va:'NỨT ĐÔNG ĐẶC (nứt nóng) — FeS có điểm chảy thấp tạo màng lỏng giữa tâm mối. Khắc phục: thêm Mn (tạo MnS).'},
{q:'EXTRA: Lowest heat input process?', a:'TIG (141)', vq:'Quá trình có heat input thấp nhất?', va:'TIG — hệ số K=0,6 thấp nhất; kiểm soát nhiệt tinh nhất.'},
{q:'EXTRA: If medium carbon steel is not preheated before/during welding, which region does it go to?', a:'Martensite', vq:'Thép C trung bình không preheat → tổ chức gì?', va:'MARTENSITE — nguội nhanh qua đường tôi → cứng, giòn, dễ nứt nguội.'},
{q:'EXTRA: Stabilised grades of austenitic stainless steel which prevent sensitisation?', a:'321 (Titanium) and 347 (Niobium)', vq:'Mác inox ổn định hóa chống nhạy cảm hóa (weld decay)?', va:'321 chứa TITAN, 347 chứa NIOBI — Ti/Nb "bắt" cacbon trước Cr → không tạo carbide crôm. (Tài liệu gốc ghi ngược Ti/Nb — bản đúng: 321=Ti, 347=Nb.)', n:'Tài liệu gốc ghi 321(Nb)/347(Ti) — bị ngược. Chuẩn: 321 = Ti, 347 = Nb.'},
{q:'EXTRA: ISO 2560-B E4xxx — what does the B indicate? And the following digit 4?', a:'B = classification by impact 27J; 4 = tested at -40°C', vq:'Trong ISO 2560-B, chữ B và số 4 chỉ gì?', va:'Theo tài liệu: B = hệ phân loại (impact 27J), số 4 = thử va đập ở -40°C. (Hệ A: 47J; hệ B: 27J.)'},
{q:'EXTRA: Which preparation has the highest distortion?', a:'Single V preparation', vq:'Kiểu vát mép nào biến dạng NHIỀU nhất?', va:'Chữ V ĐƠN — kim loại đắp lệch một phía → co ngót góc lớn. U/double-V ít biến dạng hơn.'},
{q:'EXTRA: Which preparation gives the least distortion?', a:'U preparation (double sided/balanced)', vq:'Kiểu mép nào ÍT biến dạng nhất?', va:'Mối chữ U (hoặc 2V đối xứng) — ít kim loại đắp, co ngót cân bằng 2 phía. (Từ ghi chú 2.2 câu 33.)'}
]};
